"""
MediSwift Healthcare Product Catalog Data - Part 2
Categories 6 to 10 (Heart Care, Vitamins & Supplements, Immunity Support, Skin Care, Hair Care - 65 authentic products)
"""
from decimal import Decimal

PRODUCTS_PART_2 = [
    # ---------------- 6. Heart Care ----------------
    {
        'name': 'Telma 40 Tablet',
        'slug': 'telma-40-tablet',
        'sku': 'MED-HRT-001',
        'category_slug': 'heart-care',
        'brand_name': 'Glenmark',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Telmisartan Tablets IP 40mg',
        'composition': 'Telmisartan (40mg)',
        'dosage_form': 'TABLET',
        'strength': '40mg',
        'pack_size': 'Strip of 30 tablets',
        'price': Decimal('285.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 550,
        'rating': Decimal('4.9'),
        'review_count': 2200,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Frontline angiotensin II receptor blocker for sustained 24-hour blood pressure control and cardiovascular protection.',
        'detailed_description': 'Telma 40 selectively blocks AT1 receptor subtype with an exceptionally long 24-hour terminal elimination half-life, shielding vascular beds and reducing stroke mortality.',
        'directions': 'Take 1 tablet once daily at the same time each day with or without food.',
        'warnings': 'Prescription required. Contraindicated during pregnancy. Monitor serum potassium regularly.',
        'storage_information': 'Store in original moisture-proof blister below 30°C.',
        'tags': ['blood pressure', 'telmisartan', 'hypertension', 'cardiac', 'rx']
    },
    {
        'name': 'Atorva 10 Tablet',
        'slug': 'atorva-10-tablet',
        'sku': 'MED-HRT-002',
        'category_slug': 'heart-care',
        'brand_name': 'Zydus Lifesciences',
        'manufacturer': 'Zydus Lifesciences Ltd',
        'generic_name': 'Atorvastatin Calcium Tablets IP 10mg',
        'composition': 'Atorvastatin Calcium (10mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('128.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 480,
        'rating': Decimal('4.8'),
        'review_count': 1650,
        'prescription_required': True,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Effective lipid-lowering statin reducing bad LDL cholesterol, triglycerides, and heart attack risks.',
        'detailed_description': 'Atorva inhibits HMG-CoA reductase, the rate-limiting enzyme in cholesterol biosynthesis, clearing atherogenic lipoproteins and stabilizing arterial plaques.',
        'directions': 'Take 1 tablet once daily in the evening after food.',
        'warnings': 'Prescription only. Report unexplained muscle aches or fatigue immediately to your cardiologist.',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['cholesterol', 'atorvastatin', 'statin', 'heart attack prevention', 'rx']
    },
    {
        'name': 'Ecosprin 75 Tablet',
        'slug': 'ecosprin-75-tablet',
        'sku': 'MED-HRT-003',
        'category_slug': 'heart-care',
        'brand_name': 'USV Private Limited',
        'manufacturer': 'USV Pvt Ltd',
        'generic_name': 'Aspirin Gastro-Resistant Tablets IP 75mg',
        'composition': 'Aspirin (75mg)',
        'dosage_form': 'TABLET',
        'strength': '75mg',
        'pack_size': 'Strip of 14 tablets',
        'price': Decimal('9.80'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 900,
        'rating': Decimal('4.9'),
        'review_count': 3800,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Essential daily low-dose enteric-coated blood thinner preventing coronary thrombosis and ischemic strokes.',
        'detailed_description': 'Ecosprin irreversibly acetylates platelet cyclooxygenase-1, inhibiting thromboxane A2 generation and suppressing abnormal intravascular clot formation.',
        'directions': 'Take 1 tablet daily with or immediately after meals. Swallow whole with water.',
        'warnings': 'Prescription required. Do not take if you have active bleeding or severe peptic ulcers.',
        'storage_information': 'Store in a dry location below 25°C.',
        'tags': ['aspirin', 'blood thinner', 'cardiac', 'clot prevention', 'rx']
    },
    {
        'name': 'Omron HEM 7120 Digital Blood Pressure Monitor',
        'slug': 'omron-hem-7120-bp-monitor',
        'sku': 'MED-HRT-004',
        'category_slug': 'heart-care',
        'brand_name': 'Omron Healthcare',
        'manufacturer': 'Omron Healthcare India Pvt Ltd',
        'generic_name': 'Upper Arm Automatic Digital Blood Pressure Monitor',
        'composition': 'Digital oscillometric pressure transducer with IntelliSense cuff',
        'dosage_form': 'DEVICE',
        'strength': 'Upper Arm 22-32cm Cuff',
        'pack_size': '1 Unit with Cuff and 4 AA Batteries',
        'price': Decimal('2450.00'),
        'discount_percent': Decimal('22.00'),
        'stock_quantity': 180,
        'rating': Decimal('4.9'),
        'review_count': 2950,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Clinically validated upper-arm blood pressure monitor with IntelliSense technology and hypertension indicator.',
        'detailed_description': 'Features one-touch operation, irregular heartbeat detection, body movement sensor, and automatic cuff wrap guide for accurate clinical readings at home.',
        'directions': 'Wrap cuff snugly around bare upper arm 2cm above elbow, sit calmly for 5 minutes, press Start button.',
        'warnings': 'Calibrate periodically. Do not move or speak during inflation cycle.',
        'storage_information': 'Store in protective carrying case at room temperature.',
        'tags': ['bp monitor', 'omron', 'medical device', 'hypertension', 'digital']
    },
    {
        'name': 'Concor 5 Tablet',
        'slug': 'concor-5-tablet',
        'sku': 'MED-HRT-005',
        'category_slug': 'heart-care',
        'brand_name': 'Merck India',
        'manufacturer': 'Merck Specialities Pvt Ltd / P&G Health',
        'generic_name': 'Bisoprolol Fumarate Tablets IP 5mg',
        'composition': 'Bisoprolol Fumarate (5mg)',
        'dosage_form': 'TABLET',
        'strength': '5mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('132.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 320,
        'rating': Decimal('4.8'),
        'review_count': 640,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Highly cardioselective beta-1 blocker regulating heart rate, angina, and chronic heart failure.',
        'detailed_description': 'Concor decreases cardiac sympathetic drive, resting heart rate, and myocardial oxygen consumption without significant bronchial airway resistance.',
        'directions': 'Take 1 tablet once daily in the morning before or after breakfast.',
        'warnings': 'Strict prescription medicine. Never discontinue abruptly as rebound tachycardia may occur.',
        'storage_information': 'Store below 25°C away from heat and light.',
        'tags': ['beta blocker', 'bisoprolol', 'heart rate', 'angina', 'rx']
    },
    {
        'name': 'Rosuvas 10 Tablet',
        'slug': 'rosuvas-10-tablet',
        'sku': 'MED-HRT-006',
        'category_slug': 'heart-care',
        'brand_name': 'Sun Pharma',
        'manufacturer': 'Sun Pharmaceutical Industries Ltd',
        'generic_name': 'Rosuvastatin Calcium Tablets IP 10mg',
        'composition': 'Rosuvastatin (10mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('265.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 410,
        'rating': Decimal('4.8'),
        'review_count': 1140,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Potent hydrophilic statin achieving up to 50% reduction in LDL bad cholesterol and raising HDL.',
        'detailed_description': 'High-intensity statin engineered with superior hydrophilic selectivity for hepatocytes, delivering robust reduction in circulating apolipoprotein B particles.',
        'directions': 'Take 1 tablet once daily at any time of day with water.',
        'warnings': 'Prescription required. Baseline lipid profile and liver function testing recommended.',
        'storage_information': 'Store below 30°C in a dry place.',
        'tags': ['rosuvastatin', 'cholesterol', 'cardiovascular', 'rx']
    },
    {
        'name': 'Amlong 5 Tablet',
        'slug': 'amlong-5-tablet',
        'sku': 'MED-HRT-007',
        'category_slug': 'heart-care',
        'brand_name': 'Micro Labs',
        'manufacturer': 'Micro Labs Ltd',
        'generic_name': 'Amlodipine Besilate Tablets IP 5mg',
        'composition': 'Amlodipine Besilate (5mg)',
        'dosage_form': 'TABLET',
        'strength': '5mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('44.50'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 650,
        'rating': Decimal('4.7'),
        'review_count': 1380,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Calcium channel blocker relaxing arterial vascular smooth muscle to relieve high blood pressure and chest angina.',
        'detailed_description': 'Amlong inhibits trans-membrane influx of calcium ions into vascular smooth muscle cells, causing systemic peripheral vasodilation and reduced afterload.',
        'directions': 'Take 1 tablet once daily at the same time with water.',
        'warnings': 'Prescription only. Monitor for peripheral pedal edema (ankle swelling).',
        'storage_information': 'Store below 25°C protected from light.',
        'tags': ['amlodipine', 'calcium channel blocker', 'hypertension', 'rx']
    },
    {
        'name': 'Arjuna Heart Care Herbal Capsules',
        'slug': 'arjuna-heart-care-capsules',
        'sku': 'MED-HRT-008',
        'category_slug': 'heart-care',
        'brand_name': 'Himalaya Wellness',
        'manufacturer': 'The Himalaya Drug Company',
        'generic_name': 'Terminalia Arjuna Bark Extract Capsules',
        'composition': 'Arjuna (Terminalia arjuna bark extract 250mg per capsule)',
        'dosage_form': 'CAPSULE',
        'strength': '250mg Extract',
        'pack_size': 'Bottle of 60 capsules',
        'price': Decimal('240.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 390,
        'rating': Decimal('4.7'),
        'review_count': 890,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Traditional ayurvedic cardiotonic strengthening heart muscle contraction and coronary circulation.',
        'detailed_description': 'Rich in coenzyme Q10 precursors, flavonoids, and glycosides that fortify heart myocardium, preserve endothelial elasticity, and buffer oxidative arterial stress.',
        'directions': 'Take 1 capsule twice daily with warm water after meals.',
        'warnings': 'Complimentary herbal wellness supplement. Do not replace cardiac medications without doctor consent.',
        'storage_information': 'Store in a cool dry place away from sunlight.',
        'tags': ['arjuna', 'cardiotonic', 'herbal heart', 'ayurvedic']
    },
    {
        'name': 'Dr. Morepen BP-02 Blood Pressure Monitor',
        'slug': 'dr-morepen-bp-02-monitor',
        'sku': 'MED-HRT-009',
        'category_slug': 'heart-care',
        'brand_name': 'Dr. Morepen',
        'manufacturer': 'Morepen Laboratories Ltd',
        'generic_name': 'Fully Automatic Digital Upper Arm BP Monitor',
        'composition': 'Digital oscillometric monitor with LCD display and comfort cuff',
        'dosage_form': 'DEVICE',
        'strength': 'Upper Arm 22-36cm',
        'pack_size': '1 Device with Large Cuff',
        'price': Decimal('1690.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 260,
        'rating': Decimal('4.7'),
        'review_count': 1520,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'User-friendly domestic BP monitor with 120-reading memory and WHO blood pressure classification scale.',
        'detailed_description': 'Equipped with fuzzy logic technology, dual-user memory slots, and clear acoustic notifications for effortless daily family cardiovascular monitoring.',
        'directions': 'Place cuff around left arm, rest forearm on table at heart level, and press the Power button.',
        'warnings': 'Avoid caffeine, exercise, and smoking for 30 minutes before measurement.',
        'storage_information': 'Store in dry place. Remove batteries if storing unused for over 3 months.',
        'tags': ['bp monitor', 'dr morepen', 'digital device', 'blood pressure']
    },
    {
        'name': 'Brilinta 90mg Tablet',
        'slug': 'brilinta-90mg-tablet',
        'sku': 'MED-HRT-010',
        'category_slug': 'heart-care',
        'brand_name': 'AstraZeneca',
        'manufacturer': 'AstraZeneca Pharma India Ltd',
        'generic_name': 'Ticagrelor Tablets IP 90mg',
        'composition': 'Ticagrelor (90mg)',
        'dosage_form': 'TABLET',
        'strength': '90mg',
        'pack_size': 'Strip of 14 tablets',
        'price': Decimal('980.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 150,
        'rating': Decimal('4.9'),
        'review_count': 420,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Direct-acting P2Y12 platelet inhibitor prescribed following acute coronary syndrome or stent angioplasty.',
        'detailed_description': 'Ticagrelor reversibly binds to platelet ADP receptors to prevent stent thrombosis and recurrent myocardial infarction post-angioplasty.',
        'directions': 'Take 1 tablet twice daily with or without food as instructed by your interventional cardiologist.',
        'warnings': 'Schedule H1 prescription. May cause shortness of breath (dyspnea). Do not stop without cardiologist advice.',
        'storage_information': 'Store below 30°C in original packaging.',
        'tags': ['ticagrelor', 'stent protection', 'antiplatelet', 'rx']
    },
    {
        'name': 'Dytor 10 Tablet',
        'slug': 'dytor-10-tablet',
        'sku': 'MED-HRT-011',
        'category_slug': 'heart-care',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Torsemide Tablets IP 10mg',
        'composition': 'Torsemide (10mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('94.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 370,
        'rating': Decimal('4.8'),
        'review_count': 610,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Potent loop diuretic relieving fluid retention, leg swelling, and pulmonary edema associated with heart failure.',
        'detailed_description': 'Torsemide acts on the ascending limb of the loop of Henle to inhibit sodium-potassium-chloride reabsorption, expelling excess vascular fluid.',
        'directions': 'Take 1 tablet in the morning after breakfast to avoid frequent nighttime urination.',
        'warnings': 'Prescription required. Regular electrolyte monitoring (sodium, potassium) is essential.',
        'storage_information': 'Store in dry conditions below 25°C.',
        'tags': ['diuretic', 'torsemide', 'edema', 'heart failure', 'rx']
    },
    {
        'name': 'Cardiokey CoQ10 100mg Softgels',
        'slug': 'cardiokey-coq10-100mg-softgels',
        'sku': 'MED-HRT-012',
        'category_slug': 'heart-care',
        'brand_name': 'Dr. Reddy\'s',
        'manufacturer': 'Dr. Reddy\'s Laboratories Ltd',
        'generic_name': 'Coenzyme Q10, L-Carnitine and Lycopene Softgel Capsules',
        'composition': 'Coenzyme Q10 (100mg) + L-Carnitine (500mg) + Lycopene (2.5mg)',
        'dosage_form': 'CAPSULE',
        'strength': '100mg CoQ10',
        'pack_size': 'Strip of 10 softgels',
        'price': Decimal('495.00'),
        'discount_percent': Decimal('18.00'),
        'stock_quantity': 240,
        'rating': Decimal('4.8'),
        'review_count': 510,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Essential myocardial mitochondrial energizer replenishing CoQ10 depleted by long-term statin medications.',
        'detailed_description': 'Delivers bioidentical ubiquinone to boost cardiac cellular ATP production, alleviate statin-induced muscle cramps, and promote vascular elasticity.',
        'directions': 'Take 1 softgel daily with a fat-containing meal for optimal absorption.',
        'warnings': 'Consult your doctor if pregnant or taking warfarin blood thinners.',
        'storage_information': 'Store in a cool dry place below 25°C. Do not freeze.',
        'tags': ['coq10', 'cardiac energy', 'statin relief', 'softgels']
    },
    {
        'name': 'Clopilet 75 Tablet',
        'slug': 'clopilet-75-tablet',
        'sku': 'MED-HRT-013',
        'category_slug': 'heart-care',
        'brand_name': 'Sun Pharma',
        'manufacturer': 'Sun Pharmaceutical Industries Ltd',
        'generic_name': 'Clopidogrel Tablets IP 75mg',
        'composition': 'Clopidogrel Bisulphate (75mg)',
        'dosage_form': 'TABLET',
        'strength': '75mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('145.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 490,
        'rating': Decimal('4.8'),
        'review_count': 1280,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Antiplatelet medication preventing dangerous arterial blood clots after cardiac stent or stroke.',
        'detailed_description': 'Clopidogrel permanently blocks ADP receptor signaling on blood platelets, inhibiting platelet aggregation and reducing acute ischemic events.',
        'directions': 'Take 1 tablet daily with or without food.',
        'warnings': 'Prescription required. Inform dentist or surgeon of clopidogrel therapy prior to procedures.',
        'storage_information': 'Store below 25°C in original packaging.',
        'tags': ['clopidogrel', 'blood thinner', 'antiplatelet', 'rx']
    },

    # ---------------- 7. Vitamins & Supplements ----------------
    {
        'name': 'Becosules Z Capsules',
        'slug': 'becosules-z-capsules',
        'sku': 'MED-VIT-001',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Pfizer India',
        'manufacturer': 'Pfizer Limited India',
        'generic_name': 'B-Complex with Vitamin C and Zinc',
        'composition': 'Vitamin B1, B2, B6, B12, Niacinamide, Calcium Pantothenate, Folic Acid, Vitamin C (150mg) + Zinc Sulphate (41.4mg)',
        'dosage_form': 'CAPSULE',
        'strength': 'Therapeutic Complex',
        'pack_size': 'Strip of 20 capsules',
        'price': Decimal('54.50'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 850,
        'rating': Decimal('4.9'),
        'review_count': 4200,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'India\'s #1 therapeutic B-complex with Vitamin C and Zinc for mouth ulcers, fatigue, and tissue recovery.',
        'detailed_description': 'Replenishes water-soluble vitamins critical for carbohydrate and lipid metabolism, accelerates mucosal healing in painful stomatitis, and enhances systemic immunity.',
        'directions': 'Take 1 capsule daily after a meal with plenty of water.',
        'warnings': 'May impart an intense yellow tint to urine, which is harmless riboflavin excretion.',
        'storage_information': 'Store in a cool dry place protected from light and heat.',
        'tags': ['becosules', 'b complex', 'vitamin c', 'zinc', 'mouth ulcers']
    },
    {
        'name': 'Shelcal 500 Tablet',
        'slug': 'shelcal-500-tablet',
        'sku': 'MED-VIT-002',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Torrent Pharmaceuticals',
        'manufacturer': 'Torrent Pharmaceuticals Ltd',
        'generic_name': 'Calcium and Vitamin D3 Tablets IP',
        'composition': 'Elemental Calcium (500mg from Coral Calcium) + Vitamin D3 (Cholecalciferol 250 IU)',
        'dosage_form': 'TABLET',
        'strength': '500mg/250 IU',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('131.50'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 720,
        'rating': Decimal('4.9'),
        'review_count': 3100,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'High-absorption calcium supplement for bone density, osteoporosis prevention, and joint support.',
        'detailed_description': 'Shelcal 500 supplies bioavailable calcium combined with Vitamin D3 to maximize intestinal mineral absorption, strengthening bone matrix in aging adults and expectant mothers.',
        'directions': 'Take 1 tablet daily after food, preferably after dinner.',
        'warnings': 'Avoid taking with iron supplements or thyroid medications at the exact same hour.',
        'storage_information': 'Store below 25°C away from moisture.',
        'tags': ['shelcal', 'calcium', 'vitamin d3', 'bones', 'osteoporosis']
    },
    {
        'name': 'D-Rise 60K Softgel Capsule',
        'slug': 'd-rise-60k-softgel-capsule',
        'sku': 'MED-VIT-003',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'USV Private Limited',
        'manufacturer': 'USV Pvt Ltd',
        'generic_name': 'Cholecalciferol (Vitamin D3) Softgel 60,000 IU',
        'composition': 'Cholecalciferol / Vitamin D3 (60,000 International Units)',
        'dosage_form': 'CAPSULE',
        'strength': '60,000 IU',
        'pack_size': 'Strip of 4 softgel capsules',
        'price': Decimal('185.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 680,
        'rating': Decimal('4.9'),
        'review_count': 2600,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'High-potency weekly Vitamin D3 therapy resolving severe deficiency, bone weakness, and fatigue.',
        'detailed_description': 'Delivers concentrated cholecalciferol in an oil-based softgel carrier for rapid correction of vitamin D deficits, enhancing bone calcium deposition and muscle tone.',
        'directions': 'Take 1 capsule once a week with milk or a meal for 8 to 12 weeks, or as directed by a doctor.',
        'warnings': 'Do not consume daily. Weekly dosage only unless under specialized clinical supervision.',
        'storage_information': 'Store below 25°C in a dry place. Protect from heat and moisture.',
        'tags': ['vitamin d3', 'd-rise', '60k', 'weekly vitamin', 'bone health']
    },
    {
        'name': 'Neurobion Forte Tablet',
        'slug': 'neurobion-forte-tablet',
        'sku': 'MED-VIT-004',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Procter & Gamble Health',
        'manufacturer': 'P&G Health India Ltd',
        'generic_name': 'Vitamin B1, B6 and B12 Neurotropic Formula',
        'composition': 'Vitamin B1 (10mg) + Vitamin B2 (10mg) + Vitamin B3 (45mg) + Vitamin B5 (50mg) + Vitamin B6 (3mg) + Vitamin B12 (15mcg)',
        'dosage_form': 'TABLET',
        'strength': 'Neurotropic Complex',
        'pack_size': 'Strip of 30 tablets',
        'price': Decimal('41.50'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 890,
        'rating': Decimal('4.8'),
        'review_count': 3200,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Clinically formulated neurotropic vitamins nourishing peripheral nerves and relieving tingling numbness in hands & feet.',
        'detailed_description': 'Synergistic neurotropic triad of B1, B6, and B12 promotes myelin sheath regeneration, enhances axonal neurotransmission, and alleviates diabetic neuropathic tingling.',
        'directions': 'Take 1 tablet daily with a glass of water after meals.',
        'warnings': 'Safe nutritional supplement. Store safely away from children.',
        'storage_information': 'Store below 25°C away from moisture.',
        'tags': ['neurobion', 'nerve health', 'numbness', 'b12', 'vitamin b']
    },
    {
        'name': 'Limcee 500mg Chewable Vitamin C',
        'slug': 'limcee-500mg-chewable-tablet',
        'sku': 'MED-VIT-005',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Abbott India',
        'manufacturer': 'Abbott India Ltd',
        'generic_name': 'Ascorbic Acid & Sodium Ascorbate Chewable Tablets',
        'composition': 'Ascorbic Acid (100mg) + Sodium Ascorbate (450mg equivalent to 500mg Vitamin C)',
        'dosage_form': 'TABLET',
        'strength': '500mg Orange Flavor',
        'pack_size': 'Strip of 15 chewable tablets',
        'price': Decimal('25.80'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 920,
        'rating': Decimal('4.9'),
        'review_count': 2800,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Tangy orange chewable antioxidant tablets protecting cells from oxidative stress and boosting collagen synthesis.',
        'detailed_description': 'Pure ascorbic acid delivers powerful antioxidant defense against environmental free radicals, assists iron absorption, and maintains radiant gum tissue.',
        'directions': 'Chew 1 tablet daily thoroughly. Do not swallow whole.',
        'warnings': 'Chew thoroughly before swallowing. Safe for daily wellness.',
        'storage_information': 'Keep away from humidity and direct sunlight below 25°C.',
        'tags': ['vitamin c', 'limcee', 'chewable', 'antioxidant', 'collagen']
    },
    {
        'name': 'Supradyn Daily Multivitamin Tablet',
        'slug': 'supradyn-daily-multivitamin-tablet',
        'sku': 'MED-VIT-006',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Bayer Pharmaceuticals',
        'manufacturer': 'Bayer Pharmaceuticals India',
        'generic_name': 'Multivitamin with Minerals and Trace Elements',
        'composition': '12 Essential Vitamins, 5 Trace Elements, Minerals and Amino Acids',
        'dosage_form': 'TABLET',
        'strength': 'Comprehensive Daily Formula',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('62.50'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 750,
        'rating': Decimal('4.8'),
        'review_count': 2100,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Daily micronutrient energizer banishing sluggishness, boosting stamina, and supporting daily immunity.',
        'detailed_description': 'Comprehensive formulation bridging nutritional gaps with zinc, iron, calcium, and B-vitamins for optimal energy release and cognitive vigor.',
        'directions': 'Take 1 tablet daily after breakfast with water.',
        'warnings': 'Do not exceed 1 tablet a day unless advised by a nutritionist.',
        'storage_information': 'Store below 25°C in a dry place.',
        'tags': ['supradyn', 'multivitamin', 'energy', 'daily health']
    },
    {
        'name': 'Revital H Daily Health Supplement',
        'slug': 'revital-h-daily-capsules',
        'sku': 'MED-VIT-007',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Sun Pharma',
        'manufacturer': 'Sun Pharmaceutical Industries Ltd',
        'generic_name': 'Ginseng, Multivitamins and Minerals Capsules',
        'composition': 'Standardized Panax Ginseng Extract (42.5mg) + 10 Vitamins + 9 Minerals',
        'dosage_form': 'CAPSULE',
        'strength': 'Ginseng Fortified',
        'pack_size': 'Bottle of 60 capsules',
        'price': Decimal('575.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 420,
        'rating': Decimal('4.7'),
        'review_count': 1850,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Iconic ginseng-enriched supplement enhancing physical endurance, mental alertness, and vitality.',
        'detailed_description': 'Combines adaptogenic Panax Ginseng to counter physical stress and mental fatigue with essential vitamins and minerals for active lifestyles.',
        'directions': 'Take 1 capsule daily after any main meal with a beverage.',
        'warnings': 'Take a 2-week break after 3 months of continuous consumption.',
        'storage_information': 'Keep bottle tightly closed in a cool dark place.',
        'tags': ['revital', 'ginseng', 'stamina', 'energy capsules']
    },
    {
        'name': 'Zincovit Tablet',
        'slug': 'zincovit-tablet',
        'sku': 'MED-VIT-008',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Apex Laboratories',
        'manufacturer': 'Apex Laboratories Pvt Ltd',
        'generic_name': 'Multivitamin, Multimineral with Grape Seed Extract',
        'composition': 'Grape Seed Extract (50mg) + Zinc (22mg) + Vitamins A, B, C, D, E and Minerals',
        'dosage_form': 'TABLET',
        'strength': 'Grape Seed Formula',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('115.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 680,
        'rating': Decimal('4.8'),
        'review_count': 1950,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Proanthocyanidin-rich multivitamin supporting cardiovascular health, eye vigor, and immune defense.',
        'detailed_description': 'Contains high-potency Grape Seed bioflavonoids (20x stronger than Vitamin C) alongside 22mg elemental zinc to expedite convalescence and cellular rejuvenation.',
        'directions': 'Take 1 tablet daily after food.',
        'warnings': 'Safe daily dietary supplement. Do not exceed suggested dose.',
        'storage_information': 'Store below 25°C protected from light.',
        'tags': ['zincovit', 'grape seed', 'zinc', 'convalescence']
    },
    {
        'name': 'Folvite 5mg Tablet',
        'slug': 'folvite-5mg-tablet',
        'sku': 'MED-VIT-009',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Pfizer India',
        'manufacturer': 'Pfizer Products India Pvt Ltd',
        'generic_name': 'Folic Acid Tablets IP 5mg',
        'composition': 'Folic Acid / Vitamin B9 (5mg)',
        'dosage_form': 'TABLET',
        'strength': '5mg',
        'pack_size': 'Strip of 45 tablets',
        'price': Decimal('78.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 580,
        'rating': Decimal('4.9'),
        'review_count': 1420,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Essential prenatal and hematinic folic acid preventing neural tube defects and macrocytic anemia.',
        'detailed_description': 'Crucial co-factor in purine and pyrimidine nucleotide synthesis, red blood cell erythropoiesis, and healthy fetal neurodevelopment during pregnancy.',
        'directions': 'Take 1 tablet daily with food, or as directed by an obstetrician.',
        'warnings': 'Safe prenatal vitamin. Do not miss doses during preconception and pregnancy.',
        'storage_information': 'Store below 25°C in a dry place.',
        'tags': ['folic acid', 'pregnancy', 'prenatal', 'folvite', 'anemia']
    },
    {
        'name': 'HealthKart HK Vitals Fish Oil 1000mg',
        'slug': 'hk-vitals-fish-oil-1000mg',
        'sku': 'MED-VIT-010',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'HealthKart',
        'manufacturer': 'Bright Lifecare Pvt Ltd',
        'generic_name': 'Omega 3 Fatty Acids with EPA and DHA Softgels',
        'composition': 'Fish Oil (1000mg) containing EPA (180mg) + DHA (120mg)',
        'dosage_form': 'CAPSULE',
        'strength': '1000mg Softgel',
        'pack_size': 'Bottle of 60 softgels',
        'price': Decimal('499.00'),
        'discount_percent': Decimal('25.00'),
        'stock_quantity': 430,
        'rating': Decimal('4.8'),
        'review_count': 1750,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Molecularly distilled mercury-free Omega-3 softgels lubricating joints, nourishing brain cells, and protecting heart vessels.',
        'detailed_description': 'Purified deep-sea sardine oil delivering ideal 180:120 EPA-DHA ratio with anti-reflux enteric coating to prevent fishy burps.',
        'directions': 'Take 1 softgel twice daily with meals.',
        'warnings': 'Contains fish derivatives. Caution if using blood-thinning anticoagulants.',
        'storage_information': 'Store in a cool dry place away from direct sunlight.',
        'tags': ['omega 3', 'fish oil', 'epa dha', 'joints', 'brain health']
    },
    {
        'name': 'Carbamide Forte Multivitamin for Men',
        'slug': 'carbamide-forte-multivitamin-men',
        'sku': 'MED-VIT-011',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Novus Life Sciences',
        'manufacturer': 'Novus Life Sciences Pvt Ltd',
        'generic_name': '67-Ingredient Mens Daily Performance Complex',
        'composition': 'Vitamins, Minerals, Ashwagandha, Ginseng, Ginkgo Biloba, Tribulus and Prebiotics',
        'dosage_form': 'TABLET',
        'strength': 'Men Formula',
        'pack_size': 'Bottle of 60 tablets',
        'price': Decimal('550.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 340,
        'rating': Decimal('4.7'),
        'review_count': 920,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Advanced 67-ingredient daily performance complex specifically engineered for men\'s energy, muscles, and virility.',
        'detailed_description': 'Includes botanical vitality extracts alongside complete B-vitamin spectrum and digestive prebiotics for peak athletic performance and sustained workday drive.',
        'directions': 'Take 1 tablet daily with water after lunch.',
        'warnings': 'Dietary supplement. Keep out of reach of children.',
        'storage_information': 'Store in a cool dry place with lid tightly fastened.',
        'tags': ['mens health', 'multivitamin', 'ashwagandha', 'stamina']
    },
    {
        'name': 'Livogen Adult Tonic',
        'slug': 'livogen-adult-tonic',
        'sku': 'MED-VIT-012',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Procter & Gamble Health',
        'manufacturer': 'P&G Health India Ltd',
        'generic_name': 'Iron, Folic Acid and Vitamin B12 Liquid Tonic',
        'composition': 'Ferric Ammonium Citrate (equivalent to 32.8mg Elemental Iron) + Folic Acid (0.5mg) + Vitamin B12 per 15ml',
        'dosage_form': 'LIQUID',
        'strength': 'Adult Tonic 200ml',
        'pack_size': 'Bottle of 200ml',
        'price': Decimal('165.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 380,
        'rating': Decimal('4.7'),
        'review_count': 640,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Fast-acting hematinic tonic restoring hemoglobin levels, reversing anemia, and combating iron deficiency fatigue.',
        'detailed_description': 'Gentle liquid formulation that rapidly boosts red blood cell count without inducing severe gastrointestinal constipation common with conventional iron salts.',
        'directions': 'Adults: 15ml (one tablespoonful) twice daily after meals.',
        'warnings': 'May cause dark stools, which is completely normal and harmless.',
        'storage_information': 'Store in a cool place protected from light.',
        'tags': ['iron tonic', 'anemia', 'hemoglobin', 'livogen']
    },
    {
        'name': 'Wellwoman 50+ Health Supplement',
        'slug': 'wellwoman-50-plus-supplement',
        'sku': 'MED-VIT-013',
        'category_slug': 'vitamins-supplements',
        'brand_name': 'Meyer Organics / Vitabiotics',
        'manufacturer': 'Meyer Organics Pvt Ltd',
        'generic_name': 'Specialized Nutritional Formula for Women Over 50',
        'composition': 'Lutein, CoQ10, Green Tea Extract, Biotin, Vitamin D3, B-Complex and Minerals',
        'dosage_form': 'TABLET',
        'strength': '50+ Formula',
        'pack_size': 'Box of 30 tablets',
        'price': Decimal('420.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 280,
        'rating': Decimal('4.9'),
        'review_count': 580,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Intelligent micronutrient support for active women aged 50 and above targeting heart, brain, and hormonal balance.',
        'detailed_description': 'Packed with 26 targeted bio-elements including Lutein for eye macula, Vitamin B6 for hormonal regulation, and CoQ10 for cardiovascular vitality.',
        'directions': 'Take 1 tablet daily with your main meal. Swallow with water.',
        'warnings': 'Do not chew. Not to be taken on an empty stomach.',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['womens health', 'wellwoman', 'over 50', 'longevity']
    },

    # ---------------- 8. Immunity Support ----------------
    {
        'name': 'Dabur Chyawanprash 2X Immunity',
        'slug': 'dabur-chyawanprash-2x-immunity',
        'sku': 'MED-IMM-001',
        'category_slug': 'immunity-support',
        'brand_name': 'Dabur',
        'manufacturer': 'Dabur India Ltd',
        'generic_name': 'Ayurvedic Amla and Herbal Rasayana Jam',
        'composition': 'Amla (Indian Gooseberry 41 botanical herbs) + Pippali + Ashwagandha + Shatavari',
        'dosage_form': 'OTHER',
        'strength': '1kg Family Pack',
        'pack_size': 'Jar of 1000g (1kg)',
        'price': Decimal('415.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 750,
        'rating': Decimal('4.9'),
        'review_count': 4800,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'India\'s revered ayurvedic immunity shield clinically tested to double internal disease resistance and fight seasonal illness.',
        'detailed_description': 'Crafted using an ancient recipe rich in wild Indian amla and 40+ botanical herbs that enhance natural killer (NK) cell activity and safeguard against respiratory infections.',
        'directions': 'Adults: 1 teaspoonful (approx. 12g) twice daily with warm milk or water.',
        'warnings': 'Safe for all age groups over 3 years.',
        'storage_information': 'Store in a cool dry place. Keep lid tightly closed.',
        'tags': ['chyawanprash', 'immunity', 'ayurvedic', 'amla', 'dabur']
    },
    {
        'name': 'Celin 500 Chewable Tablet',
        'slug': 'celin-500-chewable-tablet',
        'sku': 'MED-IMM-002',
        'category_slug': 'immunity-support',
        'brand_name': 'GlaxoSmithKline',
        'manufacturer': 'GSK Pharmaceuticals India',
        'generic_name': 'Vitamin C Chewable Tablets IP 500mg',
        'composition': 'Vitamin C (500mg)',
        'dosage_form': 'TABLET',
        'strength': '500mg',
        'pack_size': 'Strip of 25 tablets',
        'price': Decimal('38.50'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 820,
        'rating': Decimal('4.8'),
        'review_count': 2300,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Classic therapeutic vitamin C chewable stimulating white blood cell production and viral defense.',
        'detailed_description': 'High-dose ascorbic acid fortifies epithelial barrier defenses against pathogen entry, reduces duration of common viral colds, and speeds up wound healing.',
        'directions': 'Chew 1 tablet daily after food.',
        'warnings': 'Chew before swallowing. Do not swallow whole.',
        'storage_information': 'Store below 25°C in a dry place.',
        'tags': ['celin', 'vitamin c', 'chewable', 'immunity booster']
    },
    {
        'name': 'Himalaya Septilin Tablets',
        'slug': 'himalaya-septilin-tablets',
        'sku': 'MED-IMM-003',
        'category_slug': 'immunity-support',
        'brand_name': 'Himalaya Wellness',
        'manufacturer': 'The Himalaya Drug Company',
        'generic_name': 'Ayurvedic Immunomodulatory Formulation',
        'composition': 'Guggulu (Balsamodendron mukul 0.324g) + Maharasnadi quath (130mg) + Guduchi (Tinospora cordifolia 64mg)',
        'dosage_form': 'TABLET',
        'strength': 'Herbal Complex',
        'pack_size': 'Bottle of 60 tablets',
        'price': Decimal('195.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 480,
        'rating': Decimal('4.8'),
        'review_count': 1240,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Natural immunomodulator building physiological resistance against recurrent tonsillitis and upper airway infections.',
        'detailed_description': 'Septilin stimulates phagocytosis by activating macrophage motility, reducing susceptibility to recurring throat infections, ear aches, and chronic rhinitis.',
        'directions': 'Take 2 tablets twice daily with lukewarm water.',
        'warnings': 'Safe ayurvedic preparation. Consult physician during pregnancy.',
        'storage_information': 'Store in a cool dry place away from sunlight.',
        'tags': ['septilin', 'guduchi', 'immunomodulator', 'himalaya']
    },
    {
        'name': 'Giloy Ghanvati Immunity Tablets',
        'slug': 'giloy-ghanvati-tablets',
        'sku': 'MED-IMM-004',
        'category_slug': 'immunity-support',
        'brand_name': 'Patanjali Ayurved',
        'manufacturer': 'Patanjali Ayurved Ltd',
        'generic_name': 'Tinospora Cordifolia Pure Extract Tablets',
        'composition': 'Giloy (Tinospora cordifolia stem extract 500mg)',
        'dosage_form': 'TABLET',
        'strength': '500mg Extract',
        'pack_size': 'Bottle of 60 tablets',
        'price': Decimal('110.00'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 650,
        'rating': Decimal('4.7'),
        'review_count': 1900,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Pure Giloy (Amrita) extract purifying blood, elevating platelet counts, and treating chronic recurrent fevers.',
        'detailed_description': 'Giloy exhibits significant antipyretic, anti-inflammatory, and hepatoprotective actions, widely utilized in managing dengue fever convalescence and viral debility.',
        'directions': '1 to 2 tablets twice a day with lukewarm water.',
        'warnings': 'Natural herbal extract. Maintain adequate hydration.',
        'storage_information': 'Store in a dry location at room temperature.',
        'tags': ['giloy', 'patanjali', 'platelets', 'viral fever', 'amrita']
    },
    {
        'name': 'Baidyanath Pure Shilajit Resin 20g',
        'slug': 'baidyanath-pure-shilajit-resin-20g',
        'sku': 'MED-IMM-005',
        'category_slug': 'immunity-support',
        'brand_name': 'Baidyanath',
        'manufacturer': 'Shree Baidyanath Ayurved Bhavan Pvt Ltd',
        'generic_name': 'Purified Himalayan Asphaltum / Shilajit Resin',
        'composition': '100% Pure Shilajit Resin containing >75% Fulvic Acid and 84+ Minerals',
        'dosage_form': 'OTHER',
        'strength': 'Pure Resin 20g',
        'pack_size': 'Glass Jar of 20g with Brass Spoon',
        'price': Decimal('999.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 210,
        'rating': Decimal('4.9'),
        'review_count': 1480,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Original Himalayan gold grade Shilajit resin with 75% fulvic acid for profound stamina, anti-aging, and immune vigor.',
        'detailed_description': 'Sourced from high-altitude Himalayan cliffs, this purified resin delivers ionic trace minerals directly to cellular mitochondria, amplifying ATP generation and physiological endurance.',
        'directions': 'Dissolve a pea-sized quantity (approx. 250mg) in warm milk or green tea. Drink every morning.',
        'warnings': 'Not recommended for individuals with gout or active uric acid stones.',
        'storage_information': 'Store in a cool dry place. Keep jar tightly closed.',
        'tags': ['shilajit', 'fulvic acid', 'stamina', 'himalayan resin']
    },
    {
        'name': 'Zingavita Vitamin C + Zinc Effervescent 20s',
        'slug': 'zingavita-vitamin-c-zinc-effervescent',
        'sku': 'MED-IMM-006',
        'category_slug': 'immunity-support',
        'brand_name': 'Zingavita',
        'manufacturer': 'Adret Retail Pvt Ltd',
        'generic_name': 'Amla Extract 1000mg + Zinc 10mg Effervescent',
        'composition': 'Phyllanthus emblica (Amla Extract 1000mg) + Elemental Zinc (10mg)',
        'dosage_form': 'TABLET',
        'strength': 'Orange Fizz 20 Tablets',
        'pack_size': 'Tube of 20 effervescent tablets',
        'price': Decimal('349.00'),
        'discount_percent': Decimal('25.00'),
        'stock_quantity': 390,
        'rating': Decimal('4.8'),
        'review_count': 820,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Refreshing effervescent drink combining natural Amla Vitamin C and Zinc for rapid cellular immune hydration.',
        'detailed_description': '100% bioavailable fizzy drink gentle on the digestive tract, supplying high-potency antioxidants to eliminate free radicals and maintain glowing skin.',
        'directions': 'Drop 1 tablet in 200ml of water, wait until fully dissolved, and enjoy the sparkling orange drink.',
        'warnings': 'Do not swallow tablet directly. Cap tube tightly after removing tablet.',
        'storage_information': 'Store in a cool dry place away from heat and moisture.',
        'tags': ['effervescent', 'amla', 'fizzy drink', 'zinc', 'immunity']
    },
    {
        'name': 'Patanjali Chyawanprash Special',
        'slug': 'patanjali-chyawanprash-special',
        'sku': 'MED-IMM-007',
        'category_slug': 'immunity-support',
        'brand_name': 'Patanjali Ayurved',
        'manufacturer': 'Patanjali Ayurved Ltd',
        'generic_name': 'Ayurvedic Herbal Confection with Saffron',
        'composition': 'Fresh Amla pulp, Kesar (Saffron), Moti Pishti and 35+ medicinal herbs',
        'dosage_form': 'OTHER',
        'strength': '1kg Jar',
        'pack_size': 'Tub of 1000g (1kg)',
        'price': Decimal('325.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 580,
        'rating': Decimal('4.7'),
        'review_count': 2100,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Pure Cow Ghee and Saffron enriched chyawanprash building respiratory resistance and natural vigor.',
        'detailed_description': 'Traditional ayurvedic rasayana processed with fresh amla and enriched with Kashmiri saffron to support bronchial stamina in all family members.',
        'directions': '1 tablespoon (approx. 10g) in the morning and evening with milk.',
        'warnings': 'Safe natural food product.',
        'storage_information': 'Store in a dry location. Keep container tightly sealed.',
        'tags': ['patanjali', 'chyawanprash', 'saffron', 'herbal immunity']
    },
    {
        'name': 'Curcumin 95% with Piperine Capsules',
        'slug': 'curcumin-95-piperine-capsules',
        'sku': 'MED-IMM-008',
        'category_slug': 'immunity-support',
        'brand_name': 'Organic India',
        'manufacturer': 'Organic India Pvt Ltd',
        'generic_name': 'Standardized Turmeric Curcuminoids with Black Pepper',
        'composition': 'Curcuma longa extract (95% Curcuminoids 500mg) + Piperine (5mg)',
        'dosage_form': 'CAPSULE',
        'strength': '500mg/5mg',
        'pack_size': 'Bottle of 60 veg capsules',
        'price': Decimal('695.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 260,
        'rating': Decimal('4.9'),
        'review_count': 780,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Standardized 95% Curcumin extract fortified with Piperine for 2000% superior systemic absorption and cellular anti-inflammatory protection.',
        'detailed_description': 'Curcumin is nature\'s premier NF-kB inhibitor, suppressing chronic micro-inflammation across heart, joints, and brain cells with bioperine maximizing intestinal uptake.',
        'directions': 'Take 1 capsule twice daily with meals containing healthy fats.',
        'warnings': 'Consult physician if you have gallstones or bile duct obstruction.',
        'storage_information': 'Store in a cool dry place away from direct sunlight.',
        'tags': ['curcumin', 'turmeric', 'anti-inflammatory', 'piperine']
    },
    {
        'name': 'Dabur Honey 100% Pure',
        'slug': 'dabur-honey-100-pure',
        'sku': 'MED-IMM-009',
        'category_slug': 'immunity-support',
        'brand_name': 'Dabur',
        'manufacturer': 'Dabur India Ltd',
        'generic_name': 'NMR Tested Pure Forest Honey',
        'composition': '100% Pure Natural Bee Honey',
        'dosage_form': 'LIQUID',
        'strength': '500g Bottle',
        'pack_size': 'Squeezy Bottle of 500g',
        'price': Decimal('225.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 820,
        'rating': Decimal('4.9'),
        'review_count': 3900,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'NMR-tested pure wild honey rich in natural enzymes, antioxidants, and soothing antimicrobial properties.',
        'detailed_description': 'Strictly tested against adulteration, Dabur Honey delivers live pollen enzymes, demulcents irritated throats, and acts as a natural prebiotic sweetener.',
        'directions': 'Consume 1 tablespoon daily directly, or mix with warm water and lemon in the morning.',
        'warnings': 'Do not feed raw honey to infants under 1 year of age.',
        'storage_information': 'Store at room temperature. Do not refrigerate.',
        'tags': ['pure honey', 'dabur', 'natural sweetness', 'antioxidants']
    },
    {
        'name': 'Immune Shield Elderberry Gummies',
        'slug': 'immune-shield-elderberry-gummies',
        'sku': 'MED-IMM-010',
        'category_slug': 'immunity-support',
        'brand_name': 'Wellbeing Nutrition',
        'manufacturer': 'Wellbeing Nutrition India',
        'generic_name': 'European Black Elderberry, Zinc & Vitamin C Gummies',
        'composition': 'Sambucus nigra (Elderberry Extract 100mg) + Vitamin C (40mg) + Zinc (5mg)',
        'dosage_form': 'OTHER',
        'strength': 'Berry Flavor Gummies',
        'pack_size': 'Bottle of 30 chewable gummies',
        'price': Decimal('499.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 310,
        'rating': Decimal('4.8'),
        'review_count': 640,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Delicious pectin-based elderberry gummies packed with anthocyanins to defend against seasonal viral sniffles.',
        'detailed_description': 'European black elderberry extracts inhibit viral hemagglutinin spikes, preventing pathogen adhesion while zinc supports rapid mucosal repair.',
        'directions': 'Chew 1 gummy daily for children above 4 years, 2 gummies for adults.',
        'warnings': 'Chew thoroughly before swallowing. Keep bottle out of reach of unsupervised toddlers.',
        'storage_information': 'Store in a cool dry place below 25°C away from heat.',
        'tags': ['elderberry', 'gummies', 'kids immunity', 'chewable']
    },
    {
        'name': 'Zandu Pure Tulsi Drops',
        'slug': 'zandu-pure-tulsi-drops',
        'sku': 'MED-IMM-011',
        'category_slug': 'immunity-support',
        'brand_name': 'Emami',
        'manufacturer': 'Emami Ltd',
        'generic_name': 'Concentrated 5 Rare Tulsi Species Liquid Extract',
        'composition': 'Extracts of Vishnu Tulsi, Rama Tulsi, Shyama Tulsi, Bisva Tulsi and Van Tulsi',
        'dosage_form': 'DROPS',
        'strength': '30ml Dropper Bottle',
        'pack_size': 'Bottle of 30ml',
        'price': Decimal('165.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 520,
        'rating': Decimal('4.8'),
        'review_count': 1120,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Aromatic 5-Tulsi concentrate purifying water, boosting respiratory immunity, and detoxifying bodily systems.',
        'detailed_description': 'Distilled from five holy basil species rich in eugenol, carvacrol, and ursolic acid, promoting clear bronchial airways and resistance to ambient air pollution.',
        'directions': 'Add 1 to 2 drops in a glass of water, tea, or juice 3 to 4 times daily.',
        'warnings': 'Concentrated herbal extract. Dilute in liquid before drinking.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['tulsi drops', 'panch tulsi', 'respiratory defense', 'zandu']
    },
    {
        'name': 'Kapiva Pure Aloe Vera Juice',
        'slug': 'kapiva-pure-aloe-vera-juice',
        'sku': 'MED-IMM-012',
        'category_slug': 'immunity-support',
        'brand_name': 'Kapiva Ayurveda',
        'manufacturer': 'Adret Retail Pvt Ltd / Kapiva',
        'generic_name': 'Cold Pressed Thar Desert Aloe Vera Leaf Juice',
        'composition': 'Pure Aloe Vera (Aloe barbadensis) inner leaf fillet juice 99.6%',
        'dosage_form': 'LIQUID',
        'strength': '1000ml (1L)',
        'pack_size': 'Bottle of 1000ml',
        'price': Decimal('299.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 440,
        'rating': Decimal('4.7'),
        'review_count': 980,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Cold-pressed natural aloe vera juice promoting gut detoxification, radiant skin, and natural alkalinity.',
        'detailed_description': 'Harvested from 3-year mature Rajasthani aloe leaves and bottled within 4 hours to preserve precious acemannan polysaccharides that nurture healthy gut bacteria and immune competence.',
        'directions': 'Mix 30ml of Aloe Vera Juice in 30ml of water. Drink every morning on an empty stomach.',
        'warnings': 'Natural herbal juice. Refrigerate after opening and consume within 30 days.',
        'storage_information': 'Store in a cool place away from sunlight.',
        'tags': ['aloe vera', 'kapiva', 'gut detox', 'pure juice']
    },
    {
        'name': 'Baidyanath Amla Juice',
        'slug': 'baidyanath-amla-juice',
        'sku': 'MED-IMM-013',
        'category_slug': 'immunity-support',
        'brand_name': 'Baidyanath',
        'manufacturer': 'Shree Baidyanath Ayurved Bhavan Pvt Ltd',
        'generic_name': 'Pure Cold Pressed Indian Gooseberry Juice',
        'composition': 'Pure Amla (Emblica officinalis) fruit juice 99.8%',
        'dosage_form': 'LIQUID',
        'strength': '1000ml',
        'pack_size': 'Bottle of 1000ml',
        'price': Decimal('220.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 590,
        'rating': Decimal('4.8'),
        'review_count': 1340,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Powerhouse source of natural Vitamin C and polyphenols nourishing eyesight, hair roots, and digestive fire.',
        'detailed_description': 'Made from wild organic amla fruits rich in gallic acid and ellagitannins, providing 20x more natural vitamin C than orange juice without artificial sugars.',
        'directions': 'Dilute 20ml to 30ml in a glass of water. Consume on an empty stomach in the morning.',
        'warnings': 'Safe natural fruit juice. Consult doctor during acute hyperacidity.',
        'storage_information': 'Refrigerate after opening.',
        'tags': ['amla juice', 'vitamin c', 'baidyanath', 'hair and skin']
    },

    # ---------------- 9. Skin Care ----------------
    {
        'name': 'Cetaphil Gentle Skin Cleanser',
        'slug': 'cetaphil-gentle-skin-cleanser',
        'sku': 'MED-SKI-001',
        'category_slug': 'skin-care',
        'brand_name': 'Galderma India',
        'manufacturer': 'Galderma India Pvt Ltd',
        'generic_name': 'Hydrating Niacinamide, Panthenol and Glycerin Cleanser',
        'composition': 'Niacinamide (Vitamin B3) + Panthenol (Pro-Vitamin B5) + Hydrating Glycerin',
        'dosage_form': 'LOTION',
        'strength': 'For Dry to Normal Sensitive Skin',
        'pack_size': 'Pump Bottle of 250ml',
        'price': Decimal('645.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 480,
        'rating': Decimal('4.9'),
        'review_count': 3900,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Dermatologist-recommended non-foaming gentle cleanser preserving skin moisture barrier.',
        'detailed_description': 'Soap-free, fragrance-free micellar technology gently lifts impurities while maintaining natural stratum corneum hydration and defending against sensitivity.',
        'directions': 'Apply onto wet skin and gently massage. Rinse thoroughly with water or remove with a soft tissue.',
        'warnings': 'For external dermatological use only. Hypoallergenic and non-comedogenic.',
        'storage_information': 'Store below 25°C.',
        'tags': ['cetaphil', 'gentle cleanser', 'sensitive skin', 'dermatologist recommended']
    },
    {
        'name': 'Betnovate-N Cream',
        'slug': 'betnovate-n-cream',
        'sku': 'MED-SKI-002',
        'category_slug': 'skin-care',
        'brand_name': 'GlaxoSmithKline',
        'manufacturer': 'GSK Pharmaceuticals India',
        'generic_name': 'Betamethasone Valerate and Neomycin Skin Cream',
        'composition': 'Betamethasone Valerate (0.1% w/w) + Neomycin Sulphate (0.5% w/w)',
        'dosage_form': 'CREAM',
        'strength': '0.1% / 0.5% w/w',
        'pack_size': 'Tube of 20g',
        'price': Decimal('56.50'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 650,
        'rating': Decimal('4.7'),
        'review_count': 1850,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Topical corticosteroid and antibacterial cream treating inflammatory eczema and secondary bacterial dermatitis.',
        'detailed_description': 'Betamethasone calms erythema, swelling, and itching, while Neomycin provides targeted broad-spectrum control of superficial gram-negative skin infections.',
        'directions': 'Apply a thin layer to the affected area 2 to 3 times daily as directed by a dermatologist.',
        'warnings': 'Prescription only. Do not apply on broken skin or face for prolonged periods.',
        'storage_information': 'Store below 25°C. Do not freeze.',
        'tags': ['betnovate', 'eczema', 'corticosteroid', 'dermatitis', 'rx']
    },
    {
        'name': 'Sebamed Clear Face Cleansing Foam',
        'slug': 'sebamed-clear-face-cleansing-foam',
        'sku': 'MED-SKI-003',
        'category_slug': 'skin-care',
        'brand_name': 'Sebapharma / Sebamed',
        'manufacturer': 'USV Pvt Ltd / Sebapharma Germany',
        'generic_name': 'pH 5.5 Montaline C40 Anti-Acne Foam',
        'composition': 'Montaline C40 (Coconut oil derivative) + Panthenol (pH 5.5)',
        'dosage_form': 'LIQUID',
        'strength': 'pH 5.5 Formula',
        'pack_size': 'Pump Dispenser of 150ml',
        'price': Decimal('630.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 320,
        'rating': Decimal('4.8'),
        'review_count': 1140,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': False,
        'short_description': 'Gentle pH 5.5 foam combating acne bacteria within 5 minutes while maintaining the biological acid mantle.',
        'detailed_description': 'Montaline C40 eliminates Cutibacterium acnes bacteria without stripping the epidermal moisture barrier, soothing irritated breakouts and preventing post-acne scarring.',
        'directions': 'Dispense foam onto palms, apply to wet face, leave on for 3 to 5 minutes to allow antibacterial penetration, then rinse with water.',
        'warnings': 'Avoid direct contact with eyes. For external cosmetic dermatological use.',
        'storage_information': 'Store at room temperature away from direct heat.',
        'tags': ['sebamed', 'acne foam', 'ph 5.5', 'clear face', 'pimples']
    },
    {
        'name': 'Photostable Gold Matte Finish Sunscreen SPF 55',
        'slug': 'photostable-gold-matte-sunscreen-spf-55',
        'sku': 'MED-SKI-004',
        'category_slug': 'skin-care',
        'brand_name': 'Sun Pharma',
        'manufacturer': 'Sun Pharmaceutical Industries Ltd',
        'generic_name': 'Broad Spectrum PA++++ UVA/UVB Gel Sunscreen',
        'composition': 'Octinoxate, Uvinul A Plus, Tinosorb S, Tinosorb M, Vitamin E',
        'dosage_form': 'GEL',
        'strength': 'SPF 55 PA++++',
        'pack_size': 'Tube of 50g',
        'price': Decimal('780.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 390,
        'rating': Decimal('4.9'),
        'review_count': 1950,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Dermatologist-preferred photostable matte gel protecting against UV tanning, photoaging, and blue light.',
        'detailed_description': 'Formulated with advanced European UV filters providing 98% protection against UVA and UVB rays without leaving an oily residue or white cast on Indian skin tones.',
        'directions': 'Apply generously to face and neck 15 minutes prior to sun exposure. Reapply every 3 to 4 hours.',
        'warnings': 'For external use only. Avoid contact with eyes.',
        'storage_information': 'Store below 25°C. Do not freeze.',
        'tags': ['sunscreen', 'photostable', 'spf 55', 'matte finish', 'sun protection']
    },
    {
        'name': 'Candid Dusting Powder',
        'slug': 'candid-dusting-powder',
        'sku': 'MED-SKI-005',
        'category_slug': 'skin-care',
        'brand_name': 'Glenmark',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Clotrimazole Dusting Powder 1% w/w',
        'composition': 'Clotrimazole IP (1% w/w) in a talc base',
        'dosage_form': 'POWDER',
        'strength': '1% w/w',
        'pack_size': 'Container of 100g',
        'price': Decimal('135.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 720,
        'rating': Decimal('4.8'),
        'review_count': 2600,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'India\'s standard antifungal dusting powder preventing prickly heat, athlete\'s foot, and groin sweat rash.',
        'detailed_description': 'Clotrimazole disrupts fungal ergosterol cell membrane synthesis, keeping skin folds dry and preventing candida and tinea infections during hot and humid seasons.',
        'directions': 'Dust liberally over affected skin folds (underarms, groin, feet) twice daily after bathing.',
        'warnings': 'For external use only. Keep away from nose and mouth.',
        'storage_information': 'Store in a cool dry place with cap closed.',
        'tags': ['candid', 'fungal rash', 'prickly heat', 'clotrimazole', 'dusting powder']
    },
    {
        'name': 'Karela Neem Skin Purifier Soap',
        'slug': 'karela-neem-skin-purifier-soap',
        'sku': 'MED-SKI-006',
        'category_slug': 'skin-care',
        'brand_name': 'Himalaya Wellness',
        'manufacturer': 'The Himalaya Drug Company',
        'generic_name': 'Neem & Turmeric Cleansing Bath Bar',
        'composition': 'Azadirachta indica (Neem oil) + Curcuma longa (Turmeric)',
        'dosage_form': 'OTHER',
        'strength': '125g Bar',
        'pack_size': 'Pack of 3 bars (125g each)',
        'price': Decimal('195.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 510,
        'rating': Decimal('4.7'),
        'review_count': 1620,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Herbal antibacterial bath soap treating body acne, prickly heat, and controlling microbial body odor.',
        'detailed_description': 'Infused with cold-pressed Neem oil and Turmeric to soothe skin redness, combat bacterial microbes, and purify the dermal barrier naturally.',
        'directions': 'Lather gently over wet body during shower and rinse with clean water.',
        'warnings': 'Avoid contact with eyes. In case of contact, rinse thoroughly with water.',
        'storage_information': 'Keep on a dry soap dish after use.',
        'tags': ['neem soap', 'himalaya', 'antibacterial', 'body acne']
    },
    {
        'name': 'Epiduo Gel',
        'slug': 'epiduo-gel',
        'sku': 'MED-SKI-007',
        'category_slug': 'skin-care',
        'brand_name': 'Galderma India',
        'manufacturer': 'Galderma India Pvt Ltd',
        'generic_name': 'Adaplene and Benzoyl Peroxide Gel',
        'composition': 'Adapalene (0.1% w/w) + Benzoyl Peroxide (2.5% w/w)',
        'dosage_form': 'GEL',
        'strength': '0.1% / 2.5%',
        'pack_size': 'Pump Tube of 15g',
        'price': Decimal('645.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 180,
        'rating': Decimal('4.8'),
        'review_count': 740,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Gold standard retinoid-antimicrobial gel clearing cystic acne, blackheads, and stubborn blemishes.',
        'detailed_description': 'Combines Adapalene to normalize follicular keratinization with Benzoyl Peroxide to release oxidizing free radicals that destroy acne bacteria inside pores.',
        'directions': 'Apply a pea-sized amount over the entire clean, dry face once daily at bedtime.',
        'warnings': 'Prescription required. Use sunscreen daily as retinoids increase sun sensitivity.',
        'storage_information': 'Store below 25°C. Do not freeze.',
        'tags': ['adapalene', 'benzoyl peroxide', 'acne', 'retinoid', 'rx']
    },
    {
        'name': 'Boroline Antiseptic Ayurvedic Cream',
        'slug': 'boroline-antiseptic-ayurvedic-cream',
        'sku': 'MED-SKI-008',
        'category_slug': 'skin-care',
        'brand_name': 'G.D. Pharmaceuticals',
        'manufacturer': 'G.D. Pharmaceuticals Pvt Ltd',
        'generic_name': 'Boric Acid, Zinc Oxide and Lanolin Healing Cream',
        'composition': 'Boric Acid (1% w/w) + Zinc Oxide (3% w/w) + Anhydrous Lanolin in a petroleum base',
        'dosage_form': 'CREAM',
        'strength': 'Classic Green Tube',
        'pack_size': 'Tube of 40g',
        'price': Decimal('45.00'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 950,
        'rating': Decimal('4.9'),
        'review_count': 4200,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Legendary Indian healing cream softening cracked heels, chapped lips, dry elbows, and minor cuts overnight.',
        'detailed_description': 'Rich occlusive formula with Zinc Oxide and medical grade Lanolin that seals in natural moisture, forming a protective antimicrobial barrier over cracked skin.',
        'directions': 'Clean the affected skin well and apply liberally, especially before bedtime.',
        'warnings': 'For external use only. Safe for all skin types.',
        'storage_information': 'Store at room temperature.',
        'tags': ['boroline', 'cracked heels', 'chapped lips', 'ayurvedic healing']
    },
    {
        'name': 'Moiz Cleansing Lotion',
        'slug': 'moiz-cleansing-lotion',
        'sku': 'MED-SKI-009',
        'category_slug': 'skin-care',
        'brand_name': 'Glowderma Laboratories',
        'manufacturer': 'Glowderma Labs Pvt Ltd',
        'generic_name': 'Cetyl and Stearyl Alcohol Hydrating Lotion',
        'composition': 'Cetyl Alcohol (2.65% w/w) + Stearyl Alcohol (0.26% w/w)',
        'dosage_form': 'LOTION',
        'strength': 'Gentle Non-Foaming 200ml',
        'pack_size': 'Bottle of 200ml',
        'price': Decimal('320.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 340,
        'rating': Decimal('4.8'),
        'review_count': 680,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Ultra-gentle cleanser for atopic eczema, rosacea, and barrier-compromised delicate skin.',
        'detailed_description': 'Maintains natural epidermal lipophilic balance without lathering, suitable for post-laser or dermatological chemical peel skin recovery.',
        'directions': 'Massage gently on skin, wipe off with soft cotton or rinse gently with water.',
        'warnings': 'Hypoallergenic and fragrance-free.',
        'storage_information': 'Store below 25°C.',
        'tags': ['eczema', 'rosacea', 'gentle cleanser', 'barrier repair']
    },
    {
        'name': 'Acrofy Anti-Acne Lotion',
        'slug': 'acrofy-anti-acne-lotion',
        'sku': 'MED-SKI-010',
        'category_slug': 'skin-care',
        'brand_name': 'Dr. Reddy\'s',
        'manufacturer': 'Dr. Reddy\'s Laboratories Ltd',
        'generic_name': 'Sebum Regulator Anti-Acne Moisturizer',
        'composition': 'Seboxyl, Zinc PCA, Biosaccharide Gum-1',
        'dosage_form': 'LOTION',
        'strength': 'Oil Control 50g',
        'pack_size': 'Bottle of 50g',
        'price': Decimal('520.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 280,
        'rating': Decimal('4.8'),
        'review_count': 590,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Dermatological mattifying moisturizer controlling excess oil and sebum oxidation in acne-prone skin.',
        'detailed_description': 'Inhibits 5-alpha reductase to regulate excessive sebum production, prevents lipid peroxidation, and delivers non-greasy hydration all day.',
        'directions': 'Apply evenly over cleansed face twice daily.',
        'warnings': 'Non-comedogenic. For external dermatological use only.',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['acrofy', 'oil control', 'sebum', 'anti acne moisturizer']
    },
    {
        'name': 'Lulican 1% Cream',
        'slug': 'lulican-1-cream',
        'sku': 'MED-SKI-011',
        'category_slug': 'skin-care',
        'brand_name': 'Glenmark',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Luliconazole Cream IP 1% w/w',
        'composition': 'Luliconazole (1% w/w)',
        'dosage_form': 'CREAM',
        'strength': '1% w/w',
        'pack_size': 'Tube of 30g',
        'price': Decimal('325.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 360,
        'rating': Decimal('4.9'),
        'review_count': 890,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Next-generation broad spectrum topical antifungal eradicating ringworm, jock itch, and fungal skin infections.',
        'detailed_description': 'Luliconazole demonstrates fungicidal activity at lower concentrations than conventional azoles, requiring shorter treatment durations for complete fungal clearance.',
        'directions': 'Apply a thin layer to the affected skin and 1 inch of surrounding area once daily for 1 to 2 weeks.',
        'warnings': 'Prescription required. Complete full prescribed course to prevent fungal recurrence.',
        'storage_information': 'Store below 25°C. Do not freeze.',
        'tags': ['luliconazole', 'ringworm', 'antifungal', 'jock itch', 'rx']
    },
    {
        'name': 'Saslic DS Foaming Face Wash',
        'slug': 'saslic-ds-foaming-face-wash',
        'sku': 'MED-SKI-012',
        'category_slug': 'skin-care',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Salicylic Acid Foaming Wash 2% w/v',
        'composition': 'Salicylic Acid IP (2% w/v)',
        'dosage_form': 'LIQUID',
        'strength': '2% BHA Solution',
        'pack_size': 'Pump Dispenser of 100ml',
        'price': Decimal('440.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 410,
        'rating': Decimal('4.8'),
        'review_count': 1480,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Dermatologist-formulated 2% Salicylic acid wash exfoliating deep into pores to dissolve blackheads and acne plugs.',
        'detailed_description': 'Lipophilic Beta Hydroxy Acid (BHA) dissolves sebum buildup, accelerates cellular turnover, and clears congested comedones without irritating the skin.',
        'directions': 'Pump foam, gently massage on moist skin for 20 to 30 seconds, and wash off with lukewarm water.',
        'warnings': 'Avoid contact with eyes and mouth. Use sunscreen during daytime.',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['salicylic acid', 'saslic', 'blackheads', 'bha', 'face wash']
    },
    {
        'name': 'Vaseline Intensive Care Cocoa Glow Lotion',
        'slug': 'vaseline-intensive-care-cocoa-glow',
        'sku': 'MED-SKI-013',
        'category_slug': 'skin-care',
        'brand_name': 'Hindustan Unilever',
        'manufacturer': 'HUL India Ltd',
        'generic_name': 'Pure Cocoa Butter and Vaseline Jelly Body Lotion',
        'composition': 'Pure Cocoa Butter + Micro-droplets of Vaseline Jelly',
        'dosage_form': 'LOTION',
        'strength': '400ml Family Pump',
        'pack_size': 'Bottle of 400ml',
        'price': Decimal('385.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 780,
        'rating': Decimal('4.8'),
        'review_count': 3400,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Deep nourishing body moisturizer infusing skin with warm cocoa aroma and 48-hour radiant glow.',
        'detailed_description': 'Combines 100% pure cocoa and shea butter with microscopic droplets of Vaseline petroleum jelly, repairing winter dryness and enhancing natural skin sheen.',
        'directions': 'Apply generously across whole body after showering.',
        'warnings': 'For external body use only.',
        'storage_information': 'Store at room temperature.',
        'tags': ['vaseline', 'body lotion', 'cocoa butter', 'dry skin']
    },

    # ---------------- 10. Hair Care ----------------
    {
        'name': 'Tugain 5% Solution (Minoxidil)',
        'slug': 'tugain-5-solution-minoxidil',
        'sku': 'MED-HAI-001',
        'category_slug': 'hair-care',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Minoxidil Topical Solution USP 5% w/v',
        'composition': 'Minoxidil (5% w/v)',
        'dosage_form': 'SPRAY',
        'strength': '5% w/v',
        'pack_size': 'Bottle of 60ml with Spray & Dropper',
        'price': Decimal('890.00'),
        'discount_percent': Decimal('18.00'),
        'stock_quantity': 380,
        'rating': Decimal('4.8'),
        'review_count': 2400,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Clinically proven hair regrowth solution stimulating miniaturized hair follicles in androgenetic alopecia.',
        'detailed_description': 'Minoxidil acts as a potassium channel opener, dilating micro-vessels around hair follicles, prolonging the anagen growth phase, and halting male/female pattern baldness.',
        'directions': 'Apply 1ml twice daily directly onto clean, dry scalp in hair thinning areas. Rub gently with fingertips.',
        'warnings': 'Prescription required. Continuous daily use needed to maintain hair density.',
        'storage_information': 'Store below 25°C. Flammable; keep away from fire.',
        'tags': ['minoxidil', 'hair regrowth', 'alopecia', 'baldness', 'rx']
    },
    {
        'name': 'Scalpe Pro Anti-Dandruff Shampoo',
        'slug': 'scalpe-pro-anti-dandruff-shampoo',
        'sku': 'MED-HAI-002',
        'category_slug': 'hair-care',
        'brand_name': 'Glenmark',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Ketoconazole and Zinc Pyrithione (ZPTO) Shampoo',
        'composition': 'Ketoconazole IP (2% w/v) + Zinc Pyrithione (ZPTO 1% w/v)',
        'dosage_form': 'LIQUID',
        'strength': '2% / 1% w/v',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('295.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 540,
        'rating': Decimal('4.9'),
        'review_count': 3100,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Doctor-formulated dual-action therapeutic shampoo destroying stubborn Malassezia yeast and scalp itching.',
        'detailed_description': 'Eliminates stubborn flaking and seborrheic dermatitis while conditioning hair fibers, ensuring scalp purity and dandruff elimination in just 3 washes.',
        'directions': 'Massage onto wet scalp, leave lather on for 3 to 5 minutes to allow active antifungal action, then rinse thoroughly.',
        'warnings': 'Avoid contact with eyes. Use 2 to 3 times weekly.',
        'storage_information': 'Store below 25°C protected from light.',
        'tags': ['scalpe pro', 'dandruff', 'ketoconazole', 'zpto', 'itchy scalp']
    },
    {
        'name': 'Biotin 10,000mcg Hair Growth Tablets',
        'slug': 'biotin-10000mcg-hair-tablets',
        'sku': 'MED-HAI-003',
        'category_slug': 'hair-care',
        'brand_name': 'HealthKart',
        'manufacturer': 'Bright Lifecare Pvt Ltd',
        'generic_name': 'High Potency D-Biotin (Vitamin B7) Supplement',
        'composition': 'D-Biotin (10,000mcg) + Keratin + Zinc',
        'dosage_form': 'TABLET',
        'strength': '10,000mcg',
        'pack_size': 'Bottle of 60 tablets',
        'price': Decimal('499.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 460,
        'rating': Decimal('4.7'),
        'review_count': 1890,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Maximum potency biotin nourishing hair roots, reducing breakage, and promoting thicker strand volume.',
        'detailed_description': 'Vitamin B7 stimulates keratin protein synthesis in hair follicles and nail matrix, reinforcing structural hair resilience and boosting cuticle shine.',
        'directions': 'Take 1 tablet daily after food with a glass of water.',
        'warnings': 'Safe water-soluble dietary supplement. Keep bottle closed.',
        'storage_information': 'Store in a cool dry place away from heat.',
        'tags': ['biotin', 'hair growth', 'keratin', 'hair fall control']
    },
    {
        'name': 'Indulekha Bringha Hair Oil',
        'slug': 'indulekha-bringha-hair-oil',
        'sku': 'MED-HAI-004',
        'category_slug': 'hair-care',
        'brand_name': 'Hindustan Unilever',
        'manufacturer': 'HUL India Ltd',
        'generic_name': '100% Ayurvedic Hair Oil with Selfie Comb Applicator',
        'composition': 'Bringharaj (Eclipta alba), Svetakutaja, Amla and Virgin Coconut Oil',
        'dosage_form': 'LIQUID',
        'strength': '100ml Comb Bottle',
        'pack_size': 'Bottle of 100ml with Comb Nozzle',
        'price': Decimal('432.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 680,
        'rating': Decimal('4.8'),
        'review_count': 3600,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Clinically proven proprietary ayurvedic medicine growing new hair and arresting hair fall in 4 months.',
        'detailed_description': 'Slow-simmered virgin coconut oil extracted with Bringharaj herb and delivered directly into root follicles using the patented targeted selfie comb applicator.',
        'directions': 'Apply directly to the scalp using the comb applicator. Massage gently with fingertips. Leave overnight or for 3 hours before washing.',
        'warnings': 'For external hair and scalp application only.',
        'storage_information': 'In cold temperatures, pure coconut oil may solidify. Place bottle in warm water to liquefy.',
        'tags': ['indulekha', 'bringha', 'ayurvedic hair oil', 'hair fall']
    },
    {
        'name': 'KeraXL Hair Growth Serum',
        'slug': 'keraxl-hair-growth-serum',
        'sku': 'MED-HAI-005',
        'category_slug': 'hair-care',
        'brand_name': 'Ipca Laboratories',
        'manufacturer': 'Ipca Laboratories Ltd',
        'generic_name': 'Capixyl, Clover Extract and Peptide Complex',
        'composition': 'Biochanin A (Red Clover Extract) + Acetyl Tetrapeptide-3',
        'dosage_form': 'LIQUID',
        'strength': 'Serum 60ml',
        'pack_size': 'Bottle of 60ml with Pump',
        'price': Decimal('1120.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 220,
        'rating': Decimal('4.9'),
        'review_count': 680,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Advanced biomimetic peptide serum targeting DHT conversion and anchoring hair follicles in the scalp.',
        'detailed_description': 'Inhibits 5-alpha reductase enzyme and stimulates extracellular matrix proteins surrounding the hair bulb, reversing thinning and increasing hair density.',
        'directions': 'Spray 1ml (approx. 5 to 6 pumps) onto dry scalp in thinning areas once daily at night. Massage gently.',
        'warnings': 'Non-sticky, non-greasy formula. Safe for long term daily application.',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['capixyl', 'peptides', 'hair serum', 'dht blocker']
    },
    {
        'name': 'Nizral 2% Dandruff Solution',
        'slug': 'nizral-2-dandruff-solution',
        'sku': 'MED-HAI-006',
        'category_slug': 'hair-care',
        'brand_name': 'Johnson & Johnson',
        'manufacturer': 'Janssen Pharmaceuticals / J&J India',
        'generic_name': 'Ketoconazole Solution 2% w/v',
        'composition': 'Ketoconazole IP (2% w/v)',
        'dosage_form': 'LIQUID',
        'strength': '2% w/v',
        'pack_size': 'Bottle of 50ml',
        'price': Decimal('285.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 410,
        'rating': Decimal('4.8'),
        'review_count': 1420,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Medical grade ketoconazole solution treating chronic seborrheic dermatitis and pityriasis capitis.',
        'detailed_description': 'Disrupts fungal cell wall synthesis of pityrosporum ovale, providing long-lasting freedom from white scalp scales, grease, and scratching.',
        'directions': 'Wash hair with Nizral, leave on scalp for 5 minutes before rinsing. Use twice weekly for 2 to 4 weeks.',
        'warnings': 'Avoid contact with eyes. For scalp application only.',
        'storage_information': 'Store below 25°C protected from light.',
        'tags': ['nizral', 'ketoconazole', 'seborrhea', 'dandruff shampoo']
    },
    {
        'name': 'Sesderma Seskavel Hair Repair Mask',
        'slug': 'sesderma-seskavel-hair-repair-mask',
        'sku': 'MED-HAI-007',
        'category_slug': 'hair-care',
        'brand_name': 'Sesderma Laboratories',
        'manufacturer': 'Sesderma India Pvt Ltd',
        'generic_name': 'Hydrolyzed Keratin and Silk Protein Hair Mask',
        'composition': 'Hydrolyzed Keratin, Amino Acids, Argan Oil and Silk Protein',
        'dosage_form': 'CREAM',
        'strength': 'Intensive Repair 200ml',
        'pack_size': 'Jar of 200ml',
        'price': Decimal('1450.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 160,
        'rating': Decimal('4.9'),
        'review_count': 380,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Intense salon-grade restorative mask repairing split ends, chemical damage, and keratin-depleted strands.',
        'detailed_description': 'Micro-liposomal keratin penetrates hair cuticles to rebuild broken disulphide bonds, leaving dry and brittle hair silky, supple, and heat-protected.',
        'directions': 'Apply onto damp hair lengths after shampooing. Leave on for 10 minutes, then rinse thoroughly.',
        'warnings': 'For external hair application only.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['keratin mask', 'hair repair', 'argan oil', 'split ends']
    },
    {
        'name': 'Morr F 5% Solution',
        'slug': 'morr-f-5-solution',
        'sku': 'MED-HAI-008',
        'category_slug': 'hair-care',
        'brand_name': 'Intas Pharmaceuticals',
        'manufacturer': 'Intas Pharmaceuticals Ltd',
        'generic_name': 'Minoxidil and Finasteride Topical Solution',
        'composition': 'Minoxidil (5% w/v) + Finasteride (0.1% w/v)',
        'dosage_form': 'SPRAY',
        'strength': '5% / 0.1% w/v',
        'pack_size': 'Bottle of 60ml with Applicator',
        'price': Decimal('995.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 290,
        'rating': Decimal('4.9'),
        'review_count': 1560,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Combined Minoxidil and Finasteride topical solution blocking local scalp DHT while promoting vigorous hair regrowth.',
        'detailed_description': 'Dual-mechanism approach: Finasteride inhibits localized scalp type-II 5-alpha reductase to halt follicle shrinking, while Minoxidil supercharges microvascular nourishment.',
        'directions': 'Apply 1ml once daily at night on the dry thinning scalp area as directed by a dermatologist.',
        'warnings': 'Strict prescription medicine. Strictly contraindicated in pregnant or child-bearing women.',
        'storage_information': 'Store below 25°C. Highly flammable.',
        'tags': ['finasteride', 'minoxidil', 'hair regrowth', 'dht blocker', 'rx']
    },
    {
        'name': 'Mamaearth Onion Hair Oil',
        'slug': 'mamaearth-onion-hair-oil',
        'sku': 'MED-HAI-009',
        'category_slug': 'hair-care',
        'brand_name': 'Mamaearth',
        'manufacturer': 'Honasa Consumer Ltd',
        'generic_name': 'Red Onion Seed Oil with Redensyl',
        'composition': 'Onion Seed Oil, Redensyl, Almond Oil, Castor Oil and Bhringraj',
        'dosage_form': 'LIQUID',
        'strength': '250ml Comb Bottle',
        'pack_size': 'Bottle of 250ml with Applicator Comb',
        'price': Decimal('499.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 580,
        'rating': Decimal('4.7'),
        'review_count': 2850,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Sulfur-rich red onion oil with Redensyl strengthening hair roots and adding healthy shine.',
        'detailed_description': 'Natural sulfur from red onion extract stimulates collagen production and strengthens root shafts, while Redensyl reactivates dormant hair follicle stem cells.',
        'directions': 'Apply directly with comb nozzle, massage into scalp, leave for at least 1 hour or overnight before washing.',
        'warnings': 'Toxin-free, paraben-free and mineral oil-free.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['onion oil', 'mamaearth', 'redensyl', 'hair fall control']
    },
    {
        'name': 'Keraglo Eva Hair Growth Tablets for Women',
        'slug': 'keraglo-eva-hair-tablets-women',
        'sku': 'MED-HAI-010',
        'category_slug': 'hair-care',
        'brand_name': 'Ipca Laboratories',
        'manufacturer': 'Ipca Laboratories Ltd',
        'generic_name': 'Gamma Linolenic Acid, Multivitamins and Minerals for Women',
        'composition': 'Gamma Linolenic Acid (Borage oil 50mg) + Biotin + Green Tea Extract + Iron + Zinc',
        'dosage_form': 'TABLET',
        'strength': 'Female Hair Nutrition',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('325.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 310,
        'rating': Decimal('4.8'),
        'review_count': 820,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Dermatologist-formulated oral supplement tackling telogen effluvium and postpartum hair shedding in women.',
        'detailed_description': 'Rich in essential fatty acids and botanical antioxidants, Keraglo Eva regulates localized scalp micro-inflammation and replenishes vital nutrients required for female hair thickness.',
        'directions': 'Take 1 tablet daily after food for at least 3 months.',
        'warnings': 'Safe nutritional supplement for women. Consult gynecologist during lactation.',
        'storage_information': 'Store below 25°C away from moisture.',
        'tags': ['womens hair', 'keraglo', 'postpartum hair fall', 'biotin']
    },
    {
        'name': 'Sebamed Anti-Dandruff Shampoo',
        'slug': 'sebamed-anti-dandruff-shampoo',
        'sku': 'MED-HAI-011',
        'category_slug': 'hair-care',
        'brand_name': 'Sebapharma / Sebamed',
        'manufacturer': 'USV Pvt Ltd / Sebapharma Germany',
        'generic_name': 'Piroctone Olamine pH 5.5 Anti-Dandruff Shampoo',
        'composition': 'Piroctone Olamine + Mild Surfactants (pH 5.5)',
        'dosage_form': 'LIQUID',
        'strength': 'pH 5.5 Formula',
        'pack_size': 'Bottle of 200ml',
        'price': Decimal('610.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 370,
        'rating': Decimal('4.8'),
        'review_count': 1190,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': '100% soap and alkali-free shampoo eliminating 50% of dandruff flakes in just 14 days without stripping moisture.',
        'detailed_description': 'Formulated at pH 5.5 to stabilize the acid mantle of the scalp while Piroctone Olamine gently eliminates dandruff fungus without causing brittle, straw-like hair.',
        'directions': 'Wet hair, work a small amount into a lather in palms, wash hair gently massaging the scalp, then rinse thoroughly.',
        'warnings': 'Ideal for sensitive oily scalps prone to dandruff.',
        'storage_information': 'Store at room temperature.',
        'tags': ['sebamed', 'anti dandruff', 'piroctone olamine', 'ph 5.5']
    },
    {
        'name': 'L\'Oreal Paris Total Repair 5 Hair Serum',
        'slug': 'loreal-total-repair-5-hair-serum',
        'sku': 'MED-HAI-012',
        'category_slug': 'hair-care',
        'brand_name': 'L\'Oreal Paris',
        'manufacturer': 'L\'Oreal India Pvt Ltd',
        'generic_name': 'Ceramide-Infused Anti-Damage Hair Smoothing Serum',
        'composition': 'Ceramide Complex + Pro-Keratin Conditioning Agents',
        'dosage_form': 'LIQUID',
        'strength': 'Smoothing Formula 80ml',
        'pack_size': 'Bottle of 80ml with Pump',
        'price': Decimal('325.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 620,
        'rating': Decimal('4.8'),
        'review_count': 2700,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Instant detangling and heat protectant serum taming frizz, dullness, and rough hair flyaways.',
        'detailed_description': 'Replicates the hair\'s natural cement to fill micro-cracks in the fiber, shielding strands from blow-drying heat and humidity while adding mirror-like shine.',
        'directions': 'Rub 2 to 3 pumps between palms and distribute evenly through towel-dried or dry hair lengths.',
        'warnings': 'Avoid applying directly onto scalp roots.',
        'storage_information': 'Store away from direct sunlight.',
        'tags': ['hair serum', 'loreal', 'heat protectant', 'frizz control']
    },
    {
        'name': 'Cipla 8X Anti-Dandruff Shampoo',
        'slug': 'cipla-8x-anti-dandruff-shampoo',
        'sku': 'MED-HAI-013',
        'category_slug': 'hair-care',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Ciclopirox Olamine and Zinc Pyrithione Shampoo',
        'composition': 'Ciclopirox Olamine (1% w/v) + Zinc Pyrithione (1% w/v) with Aloe Vera',
        'dosage_form': 'LIQUID',
        'strength': '1% / 1% w/v',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('310.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 350,
        'rating': Decimal('4.8'),
        'review_count': 940,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Intensive broad-spectrum antifungal shampoo with aloe vera soothing stubborn flaking and scalp erythema.',
        'detailed_description': 'Combines Ciclopirox Olamine to halt fungal amino acid transport with Zinc Pyrithione to regulate scalp cell turnover and prevent immediate flaking relapse.',
        'directions': 'Wet hair, apply shampoo, massage into scalp for 3 minutes, then rinse thoroughly. Use twice weekly.',
        'warnings': 'For scalp application only. Rinse with water if contact with eyes occurs.',
        'storage_information': 'Store below 25°C away from direct heat.',
        'tags': ['8x shampoo', 'ciclopirox', 'dandruff', 'cipla']
    },
]
