"""
MediSwift Healthcare Product Catalog Data - Part 1
Categories 1 to 10 (130 authentic products)
"""
from decimal import Decimal

CATEGORIES_PART_1 = [
    {
        'name': 'Pain Relief',
        'slug': 'pain-relief',
        'description': 'Targeted analgesics, topical sprays, muscle relaxants, and anti-inflammatory formulations for acute and chronic pain management.'
    },
    {
        'name': 'Fever & Cold',
        'slug': 'fever-cold',
        'description': 'Antipyretics, decongestants, cold syrups, and combination relief medications formulated to combat flu and viral fevers.'
    },
    {
        'name': 'Cough & Respiratory',
        'slug': 'cough-respiratory',
        'description': 'Bronchodilators, antitussives, mucolytics, inhalers, and soothing herbal syrups for bronchial and pulmonary wellness.'
    },
    {
        'name': 'Digestive Health',
        'slug': 'digestive-health',
        'description': 'Antacids, proton pump inhibitors, probiotics, laxatives, and enzymatic formulations for gut balance and acidity relief.'
    },
    {
        'name': 'Diabetes Care',
        'slug': 'diabetes-care',
        'description': 'Oral hypoglycemic agents, monitoring glucose strips, insulin accessories, and specialized diabetic foot & nerve care.'
    },
    {
        'name': 'Heart Care',
        'slug': 'heart-care',
        'description': 'Cardiovascular therapeutics, antihypertensives, cholesterol regulators, blood thinners, and digital cardiac monitors.'
    },
    {
        'name': 'Vitamins & Supplements',
        'slug': 'vitamins-supplements',
        'description': 'High-potency multivitamins, essential mineral complexes, Vitamin D3, calcium, and cellular metabolic enhancers.'
    },
    {
        'name': 'Immunity Support',
        'slug': 'immunity-support',
        'description': 'Traditional ayurvedic rasayanas, herbal extracts, zinc tablets, and scientifically validated immune defence boosters.'
    },
    {
        'name': 'Skin Care',
        'slug': 'skin-care',
        'description': 'Dermatological barrier repair creams, medical cleansers, antifungal topicals, acne therapeutics, and clinical sun protection.'
    },
    {
        'name': 'Hair Care',
        'slug': 'hair-care',
        'description': 'Follicle stimulants, ketoconazole anti-dandruff solutions, hair peptide serums, and clinically proven hair loss treatments.'
    },
]

PRODUCTS_PART_1 = [
    # ---------------- 1. Pain Relief ----------------
    {
        'name': 'Combiflam Tablet',
        'slug': 'combiflam-tablet',
        'sku': 'MED-PAIN-001',
        'category_slug': 'pain-relief',
        'brand_name': 'Sanofi India',
        'manufacturer': 'Sanofi India Ltd',
        'generic_name': 'Ibuprofen and Paracetamol',
        'composition': 'Ibuprofen (400mg) + Paracetamol (325mg)',
        'dosage_form': 'TABLET',
        'strength': '400mg/325mg',
        'pack_size': 'Strip of 20 tablets',
        'price': Decimal('52.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 450,
        'rating': Decimal('4.6'),
        'review_count': 920,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Fast dual-action painkiller and antipyretic for muscular, toothache, and headache relief.',
        'detailed_description': 'Combiflam Tablet combines Ibuprofen (NSAID) and Paracetamol (analgesic & antipyretic). It inhibits prostaglandins synthesis to alleviate pain, reduce inflammation, and bring down elevated body temperature.',
        'directions': 'Take 1 tablet after meals with a glass of water. Do not exceed 3 tablets in 24 hours.',
        'warnings': 'Avoid use in active peptic ulcer disease or severe kidney/liver impairment. Do not take with other paracetamol products.',
        'storage_information': 'Store below 25°C in a dry place away from direct sunlight.',
        'tags': ['pain', 'ibuprofen', 'paracetamol', 'headache', 'body pain']
    },
    {
        'name': 'Volini Pain Relief Gel',
        'slug': 'volini-pain-relief-gel',
        'sku': 'MED-PAIN-002',
        'category_slug': 'pain-relief',
        'brand_name': 'Sun Pharma',
        'manufacturer': 'Sun Pharmaceutical Industries Ltd',
        'generic_name': 'Diclofenac Diethylamine, Linseed Oil, Methyl Salicylate & Menthol Gel',
        'composition': 'Diclofenac Diethylamine (1.16% w/w) + Methyl Salicylate (10% w/w) + Menthol (5% w/w)',
        'dosage_form': 'GEL',
        'strength': '1.16% w/w',
        'pack_size': 'Tube of 75g',
        'price': Decimal('245.00'),
        'discount_percent': Decimal('18.00'),
        'stock_quantity': 320,
        'rating': Decimal('4.8'),
        'review_count': 1420,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Deep penetrating analgesic gel for rapid relief from back pain, sprains, and joint stiffness.',
        'detailed_description': 'Volini Gel penetrates deep into inflamed tissues using micro-gel technology. Formulated with Diclofenac to suppress localized inflammation and Menthol for an instant cooling sensation.',
        'directions': 'Apply 3 to 4 times daily to the affected area. Gently massage until absorbed.',
        'warnings': 'For external use only. Do not apply on broken skin or open wounds. Wash hands after application.',
        'storage_information': 'Keep tube tightly closed. Store at room temperature away from heat.',
        'tags': ['gel', 'diclofenac', 'joint pain', 'sprain', 'backache']
    },
    {
        'name': 'Zerodol-SP Tablet',
        'slug': 'zerodol-sp-tablet',
        'sku': 'MED-PAIN-003',
        'category_slug': 'pain-relief',
        'brand_name': 'Ipca Laboratories',
        'manufacturer': 'Ipca Laboratories Ltd',
        'generic_name': 'Aceclofenac, Paracetamol and Serratiopeptidase',
        'composition': 'Aceclofenac (100mg) + Paracetamol (325mg) + Serratiopeptidase (15mg)',
        'dosage_form': 'TABLET',
        'strength': '100mg/325mg/15mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('135.50'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 280,
        'rating': Decimal('4.7'),
        'review_count': 610,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Powerful anti-inflammatory and proteolytic tablet for severe trauma, post-surgery, and arthritis swelling.',
        'detailed_description': 'Zerodol-SP is a triple-action formulation where Aceclofenac and Paracetamol halt inflammatory cascades, while Serratiopeptidase breaks down abnormal proteins at the inflammation site to reduce edema.',
        'directions': 'Take 1 tablet twice daily after food, or as directed by an orthopedic specialist.',
        'warnings': 'Requires prescription. May cause stomach irritation. Caution in elderly and patients with cardiovascular disease.',
        'storage_information': 'Store in a cool, dry place protected from light and moisture.',
        'tags': ['aceclofenac', 'serratiopeptidase', 'inflammation', 'orthopedic', 'rx']
    },
    {
        'name': 'Moov Fast Pain Relief Spray',
        'slug': 'moov-fast-pain-relief-spray',
        'sku': 'MED-PAIN-004',
        'category_slug': 'pain-relief',
        'brand_name': 'Reckitt Benckiser',
        'manufacturer': 'Reckitt Benckiser Healthcare India',
        'generic_name': 'Herbal Ayurvedic Pain Relief Spray',
        'composition': 'Wintergreen Oil (15%) + Pudinah Ka Phool (6%) + Nilgiri Tel (2%) + Tarpin Ka Tel (3%)',
        'dosage_form': 'SPRAY',
        'strength': '80g',
        'pack_size': 'Can of 80g',
        'price': Decimal('210.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 190,
        'rating': Decimal('4.5'),
        'review_count': 480,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Instant aerosol spray for acute muscle spasms, back stiffness, and sports injuries.',
        'detailed_description': 'Moov Spray uses an ayurvedic warming formula that improves local microcirculation and relaxes strained muscle fibers within minutes.',
        'directions': 'Shake can well. Spray from a distance of 5 cm on the affected area 3 to 4 times a day.',
        'warnings': 'Flammable aerosol. Do not puncture can. Avoid inhalation or contact with eyes.',
        'storage_information': 'Pressurized container. Keep away from direct sunlight and temperatures exceeding 50°C.',
        'tags': ['spray', 'muscle spasm', 'ayurvedic', 'sports relief']
    },
    {
        'name': 'Brufen 400 Tablet',
        'slug': 'brufen-400-tablet',
        'sku': 'MED-PAIN-005',
        'category_slug': 'pain-relief',
        'brand_name': 'Abbott India',
        'manufacturer': 'Abbott Healthcare Pvt Ltd',
        'generic_name': 'Ibuprofen 400mg',
        'composition': 'Ibuprofen (400mg)',
        'dosage_form': 'TABLET',
        'strength': '400mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('32.40'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 400,
        'rating': Decimal('4.4'),
        'review_count': 310,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Standard non-steroidal anti-inflammatory tablet for moderate pain and rheumatoid flare-ups.',
        'detailed_description': 'Brufen 400 contains Ibuprofen which acts on cyclooxygenase pathways to suppress pain, tender joints, and acute dental aches.',
        'directions': 'Take 1 tablet every 8 hours with milk or food to minimize gastrointestinal upset.',
        'warnings': 'Use under medical supervision. Not recommended during third trimester of pregnancy.',
        'storage_information': 'Store below 30°C in the original blister pack.',
        'tags': ['ibuprofen', 'nsaid', 'rheumatoid', 'rx']
    },
    {
        'name': 'Omnigel Topical Gel',
        'slug': 'omnigel-topical-gel',
        'sku': 'MED-PAIN-006',
        'category_slug': 'pain-relief',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Diclofenac, Virgin Linseed Oil, Methyl Salicylate and Menthol Gel',
        'composition': 'Diclofenac (1.16% w/w) + Linseed Oil (3% w/w) + Menthol (5% w/w)',
        'dosage_form': 'GEL',
        'strength': '1.16% w/w',
        'pack_size': 'Tube of 50g',
        'price': Decimal('165.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 260,
        'rating': Decimal('4.7'),
        'review_count': 540,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Specialized gel for osteoarthritis stiffness, frozen shoulder, and chronic joint ache.',
        'detailed_description': 'Omnigel incorporates virgin linseed oil to condition inflamed ligaments while Diclofenac provides sustained anti-inflammatory analgesia.',
        'directions': 'Massage gently over clean, dry affected joint 3 to 4 times a day.',
        'warnings': 'External use only. Avoid wrapping tightly with non-breathable dressings.',
        'storage_information': 'Store in a cool dry place. Do not freeze.',
        'tags': ['omnigel', 'joint ache', 'osteoarthritis', 'topical']
    },
    {
        'name': 'Ultracet Tablet',
        'slug': 'ultracet-tablet',
        'sku': 'MED-PAIN-007',
        'category_slug': 'pain-relief',
        'brand_name': 'Johnson & Johnson',
        'manufacturer': 'Janssen Pharmaceuticals / J&J India',
        'generic_name': 'Tramadol Hydrochloride and Paracetamol',
        'composition': 'Tramadol HCl (37.5mg) + Paracetamol (325mg)',
        'dosage_form': 'TABLET',
        'strength': '37.5mg/325mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('310.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 140,
        'rating': Decimal('4.6'),
        'review_count': 220,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Controlled central analgesic for moderate to severe acute musculoskeletal and post-surgical pain.',
        'detailed_description': 'Ultracet binds to mu-opioid receptors and weakly inhibits reuptake of norepinephrine and serotonin, augmented by paracetamol for multimodal analgesic control.',
        'directions': 'Strictly as prescribed by a licensed physician. Do not crush or chew.',
        'warnings': 'Schedule H1 prescription. May cause drowsiness or dizziness. Avoid driving or alcohol consumption.',
        'storage_information': 'Store securely between 15°C and 30°C.',
        'tags': ['tramadol', 'severe pain', 'schedule-h1', 'rx']
    },
    {
        'name': 'Ibugesic Plus Suspension',
        'slug': 'ibugesic-plus-suspension',
        'sku': 'MED-PAIN-008',
        'category_slug': 'pain-relief',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Ibuprofen and Paracetamol Oral Suspension',
        'composition': 'Each 5ml: Ibuprofen (100mg) + Paracetamol (162.5mg)',
        'dosage_form': 'SUSPENSION',
        'strength': '100mg/162.5mg per 5ml',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('48.50'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 310,
        'rating': Decimal('4.7'),
        'review_count': 390,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Pediatric oral suspension for prompt reduction of high fever, teething discomfort, and juvenile aches.',
        'detailed_description': 'Formulated with calibrated pediatric suspension buffers for gentle gastric tolerability while providing dual-action fever and pain relief.',
        'directions': 'Dose strictly as per pediatric body weight chart using the measuring cup provided.',
        'warnings': 'Not for infants under 6 months without doctor supervision. Shake well before use.',
        'storage_information': 'Store below 25°C. Keep bottle tightly closed.',
        'tags': ['pediatric', 'syrup', 'fever', 'teething', 'rx']
    },
    {
        'name': 'Zandu Balm Ultra Power',
        'slug': 'zandu-balm-ultra-power',
        'sku': 'MED-PAIN-009',
        'category_slug': 'pain-relief',
        'brand_name': 'Emami',
        'manufacturer': 'Emami Ltd',
        'generic_name': 'Ayurvedic Fast Action Pain Balm',
        'composition': 'Gaultheria Oil (20%) + Menthol (16%) + Clove Oil (5%) + Camphor (10%)',
        'dosage_form': 'OINTMENT',
        'strength': '25ml / 25g',
        'pack_size': 'Pot of 25ml',
        'price': Decimal('115.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 500,
        'rating': Decimal('4.8'),
        'review_count': 1850,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Trusted heritage herbal balm delivering intense warmth to relieve persistent headaches and body aches.',
        'detailed_description': 'Infused with Gaultheria and Clove oil, this balm provides rapid counter-irritant soothing therapy for tension headaches and neck stiffness.',
        'directions': 'Apply a small amount to forehead and temples. Gently massage in circular motions.',
        'warnings': 'For external use only. Keep away from eyes and mucous membranes.',
        'storage_information': 'Store in a cool dry place away from flame and sunlight.',
        'tags': ['balm', 'headache', 'ayurvedic', 'clove oil']
    },
    {
        'name': 'Dynapar QPS Pain Relief Solution',
        'slug': 'dynapar-qps-solution',
        'sku': 'MED-PAIN-010',
        'category_slug': 'pain-relief',
        'brand_name': 'Troikaa Pharmaceuticals',
        'manufacturer': 'Troikaa Pharmaceuticals Ltd',
        'generic_name': 'Diclofenac Diethylamine Topical Solution',
        'composition': 'Diclofenac Diethylamine (4% w/v) Quick Penetrating Solution',
        'dosage_form': 'SPRAY',
        'strength': '4% w/v',
        'pack_size': 'Spray Bottle of 30ml',
        'price': Decimal('285.00'),
        'discount_percent': Decimal('14.00'),
        'stock_quantity': 180,
        'rating': Decimal('4.9'),
        'review_count': 320,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Advanced non-greasy quick penetrating solution for severe localized musculoskeletal pain.',
        'detailed_description': 'Patented QPS technology delivers 4x higher tissue penetration than conventional gels, targeting deep-seated nerve and musculoskeletal pain.',
        'directions': 'Spray 3 to 4 metered doses directly on affected site without rubbing vigorously.',
        'warnings': 'Do not apply over cuts, rashes or eczema. Prescription required.',
        'storage_information': 'Store below 25°C. Do not freeze.',
        'tags': ['dynapar', 'topical spray', 'deep pain', 'rx']
    },
    {
        'name': 'Amrutanjan Extra Power Pain Balm',
        'slug': 'amrutanjan-extra-power-balm',
        'sku': 'MED-PAIN-011',
        'category_slug': 'pain-relief',
        'brand_name': 'Amrutanjan Health Care',
        'manufacturer': 'Amrutanjan Health Care Ltd',
        'generic_name': 'Ayurvedic Headache & Cold Balm',
        'composition': 'Pudina Ka Phool (15%) + Gandhapura Patra Taila (15%) + Nilgiri Ka Tel (3%)',
        'dosage_form': 'OINTMENT',
        'strength': '50ml',
        'pack_size': 'Jar of 50ml',
        'price': Decimal('150.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 410,
        'rating': Decimal('4.7'),
        'review_count': 740,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Classic herbal formula for relieving stubborn headaches and nasal congestion.',
        'detailed_description': 'Combines ten botanical essential oils that synergistically open nasal passages and ease vascular tension across the brow.',
        'directions': 'Massage gently over forehead, neck, or chest before sleep.',
        'warnings': 'Avoid contact with eyes. Do not bandage tightly.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['amrutanjan', 'headache', 'herbal', 'classic']
    },
    {
        'name': 'Ketorol DT Tablet',
        'slug': 'ketorol-dt-tablet',
        'sku': 'MED-PAIN-012',
        'category_slug': 'pain-relief',
        'brand_name': 'Dr. Reddy\'s',
        'manufacturer': 'Dr. Reddy\'s Laboratories Ltd',
        'generic_name': 'Ketorolac Tromethamine Dispersible Tablets',
        'composition': 'Ketorolac Tromethamine (10mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('148.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 220,
        'rating': Decimal('4.8'),
        'review_count': 410,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Rapid dispersible non-opioid tablet for acute dental extraction and severe short-term pain.',
        'detailed_description': 'Ketorolac is a potent NSAID that acts within 20 minutes to interrupt acute inflammatory cascades without central sedative effects.',
        'directions': 'Disperse 1 tablet in a teaspoon of water before drinking. Maximum therapy duration: 5 days.',
        'warnings': 'Strict prescription required. Contraindicated in peptic ulcer or renal insufficiency.',
        'storage_information': 'Protect from light and moisture. Store below 25°C.',
        'tags': ['ketorolac', 'dental pain', 'acute', 'rx']
    },
    {
        'name': 'Flamar 3D Tablet',
        'slug': 'flamar-3d-tablet',
        'sku': 'MED-PAIN-013',
        'category_slug': 'pain-relief',
        'brand_name': 'Mankind Pharma',
        'manufacturer': 'Mankind Pharma Ltd',
        'generic_name': 'Trypsin, Bromelain, Rutoside Trihydrate and Diclofenac',
        'composition': 'Trypsin (48mg) + Bromelain (90mg) + Rutoside (100mg) + Diclofenac Potassium (50mg)',
        'dosage_form': 'TABLET',
        'strength': 'Combination',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('225.00'),
        'discount_percent': Decimal('16.00'),
        'stock_quantity': 160,
        'rating': Decimal('4.7'),
        'review_count': 190,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Enzyme-enhanced anti-inflammatory therapy for wound hematoma, edema, and orthopaedic surgery recovery.',
        'detailed_description': 'Enzymatic duo of Trypsin and Bromelain accelerates microthrombi clearance and fibrinolysis, working with Diclofenac to eliminate post-traumatic swelling.',
        'directions': 'Take 1 tablet twice daily 1 hour before meals.',
        'warnings': 'Requires prescription. Monitor for allergic reactions to pineapple-derived bromelain.',
        'storage_information': 'Store in a dry location below 25°C.',
        'tags': ['enzymes', 'anti-edema', 'orthopedic', 'rx']
    },

    # ---------------- 2. Fever & Cold ----------------
    {
        'name': 'Dolo 650 Tablet',
        'slug': 'dolo-650-tablet',
        'sku': 'MED-FEV-001',
        'category_slug': 'fever-cold',
        'brand_name': 'Micro Labs',
        'manufacturer': 'Micro Labs Ltd',
        'generic_name': 'Paracetamol 650mg',
        'composition': 'Paracetamol (650mg)',
        'dosage_form': 'TABLET',
        'strength': '650mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('34.50'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 900,
        'rating': Decimal('4.9'),
        'review_count': 3200,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'India\'s most trusted antipyretic for high fever, dengue chills, body aches, and post-vaccination relief.',
        'detailed_description': 'Dolo 650 provides consistent plasma paracetamol levels that reset the hypothalamic thermoregulatory center and alleviate severe bodily malaise.',
        'directions': 'Take 1 tablet every 6 to 8 hours as needed. Maximum 4 tablets in 24 hours.',
        'warnings': 'Do not exceed recommended dose. Overdose can cause severe liver damage.',
        'storage_information': 'Store below 30°C in a dry place.',
        'tags': ['paracetamol', 'fever', 'chills', 'viral fever', 'headache']
    },
    {
        'name': 'Crocin 650 Advance Tablet',
        'slug': 'crocin-650-advance-tablet',
        'sku': 'MED-FEV-002',
        'category_slug': 'fever-cold',
        'brand_name': 'GlaxoSmithKline',
        'manufacturer': 'GSK Consumer Healthcare India',
        'generic_name': 'Paracetamol 650mg with Optizorb Technology',
        'composition': 'Paracetamol (650mg)',
        'dosage_form': 'TABLET',
        'strength': '650mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('35.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 720,
        'rating': Decimal('4.8'),
        'review_count': 2100,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Fast-dissolving paracetamol tablet engineered with Optizorb for release in just 5 minutes.',
        'detailed_description': 'Crocin Advance features Optizorb technology which rapidly disintegrates in the stomach, promoting quicker absorption and prompt reduction of elevated body temperature.',
        'directions': '1 tablet every 4 to 6 hours as required. Swallow whole with water.',
        'warnings': 'Do not use concomitantly with other paracetamol-containing medications.',
        'storage_information': 'Store below 25°C away from humidity.',
        'tags': ['crocin', 'fast acting', 'fever', 'optizorb']
    },
    {
        'name': 'Cheston Cold Tablet',
        'slug': 'cheston-cold-tablet',
        'sku': 'MED-FEV-003',
        'category_slug': 'fever-cold',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Cetirizine, Paracetamol and Phenylephrine',
        'composition': 'Cetirizine (5mg) + Paracetamol (325mg) + Phenylephrine HCl (10mg)',
        'dosage_form': 'TABLET',
        'strength': '5mg/325mg/10mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('52.50'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 550,
        'rating': Decimal('4.7'),
        'review_count': 1120,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Comprehensive triple-action cold tablet for runny nose, nasal blockage, sneezing, and fever.',
        'detailed_description': 'Cheston Cold integrates Cetirizine (anti-histamine), Phenylephrine (nasal decongestant), and Paracetamol to treat multifaceted seasonal flu symptoms.',
        'directions': 'Take 1 tablet twice daily after meals, or as advised by a doctor.',
        'warnings': 'May cause slight drowsiness. Caution in hypertension or glaucoma patients.',
        'storage_information': 'Store in a dry location below 30°C.',
        'tags': ['cold', 'runny nose', 'decongestant', 'rx']
    },
    {
        'name': 'Sinarest New Tablet',
        'slug': 'sinarest-new-tablet',
        'sku': 'MED-FEV-004',
        'category_slug': 'fever-cold',
        'brand_name': 'Centaur Pharmaceuticals',
        'manufacturer': 'Centaur Pharmaceuticals Pvt Ltd',
        'generic_name': 'Chlorpheniramine Maleate, Paracetamol, Phenylephrine and Caffeine',
        'composition': 'Paracetamol (500mg) + Phenylephrine (10mg) + CPM (2mg) + Caffeine (30mg)',
        'dosage_form': 'TABLET',
        'strength': 'Combination',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('68.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 480,
        'rating': Decimal('4.7'),
        'review_count': 940,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Targeted sinus and cold relief tablet with caffeine to counteract sedative lethargy.',
        'detailed_description': 'Sinarest addresses sinus congestion, headache, and allergic rhinorrhea while moderate caffeine enhances analgesic efficiency and maintains alertness.',
        'directions': '1 tablet 2 to 3 times a day after meals.',
        'warnings': 'Rx required. Not advised for patients with unmonitored cardiovascular disorders.',
        'storage_information': 'Store protected from light and heat.',
        'tags': ['sinus', 'headache', 'cold', 'caffeine', 'rx']
    },
    {
        'name': 'Vicks VapoRub Balm',
        'slug': 'vicks-vaporub-balm',
        'sku': 'MED-FEV-005',
        'category_slug': 'fever-cold',
        'brand_name': 'Procter & Gamble',
        'manufacturer': 'P&G Hygiene and Health Care Ltd',
        'generic_name': 'Menthol, Camphor & Eucalyptus Inhalation Ointment',
        'composition': 'Camphor (5.26% w/w) + Menthol (2.82% w/w) + Eucalyptus Oil (1.33% w/w)',
        'dosage_form': 'OINTMENT',
        'strength': '50ml / 50g',
        'pack_size': 'Jar of 50ml',
        'price': Decimal('175.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 800,
        'rating': Decimal('4.9'),
        'review_count': 3800,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Time-tested vapor rub for clearing blocked nasal passages and soothing chest heaviness.',
        'detailed_description': 'Aromatic therapeutic vapors release upon topical chest rub or steam inhalation, calming irritable airways and promoting peaceful nocturnal breathing.',
        'directions': 'Rub gently on chest, neck, and back. Or add 1 teaspoon to steaming water for steam inhalation.',
        'warnings': 'For external application only. Never heat the mixture directly or microwave.',
        'storage_information': 'Keep lid firmly sealed. Store in a cool place.',
        'tags': ['vicks', 'steam inhalation', 'chest rub', 'congestion']
    },
    {
        'name': 'Calpol 500mg Tablet',
        'slug': 'calpol-500mg-tablet',
        'sku': 'MED-FEV-006',
        'category_slug': 'fever-cold',
        'brand_name': 'GlaxoSmithKline',
        'manufacturer': 'GSK Pharmaceuticals India',
        'generic_name': 'Paracetamol 500mg',
        'composition': 'Paracetamol (500mg)',
        'dosage_form': 'TABLET',
        'strength': '500mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('19.80'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 650,
        'rating': Decimal('4.7'),
        'review_count': 820,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Gentle antipyretic for mild fevers, tension headaches, and everyday aches.',
        'detailed_description': 'Calpol 500 offers calibrated pain and fever control with excellent gastric tolerability, suitable for elderly and sensitive stomachs.',
        'directions': '1 to 2 tablets every 6 hours with a sip of water.',
        'warnings': 'Do not take with other medicines containing paracetamol.',
        'storage_information': 'Store below 25°C in dry conditions.',
        'tags': ['calpol', 'paracetamol', 'mild fever', 'otc']
    },
    {
        'name': 'Maxtra Oral Drops',
        'slug': 'maxtra-oral-drops',
        'sku': 'MED-FEV-007',
        'category_slug': 'fever-cold',
        'brand_name': 'Zuventus Healthcare',
        'manufacturer': 'Zuventus Healthcare Ltd',
        'generic_name': 'Phenylephrine and Chlorpheniramine Drops',
        'composition': 'Each ml: Phenylephrine HCl (2.5mg) + Chlorpheniramine Maleate (1mg)',
        'dosage_form': 'DROPS',
        'strength': '2.5mg/1mg per ml',
        'pack_size': 'Dropper Bottle of 15ml',
        'price': Decimal('78.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 240,
        'rating': Decimal('4.8'),
        'review_count': 380,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Infant drops for nasal stuffiness, allergic sneezing, and blocked airways.',
        'detailed_description': 'Specially formulated pediatric formulation calibrated for infant upper respiratory allergy symptoms and decongestion.',
        'directions': 'Use calibrated dropper strictly as recommended by the pediatrician.',
        'warnings': 'Prescription medication. Do not exceed suggested pediatric dose.',
        'storage_information': 'Store below 25°C. Keep out of reach of children.',
        'tags': ['infant drops', 'cold', 'pediatric', 'rx']
    },
    {
        'name': 'Otrivin Oxy Fast Relief Nasal Spray',
        'slug': 'otrivin-oxy-fast-relief-nasal-spray',
        'sku': 'MED-FEV-008',
        'category_slug': 'fever-cold',
        'brand_name': 'GlaxoSmithKline',
        'manufacturer': 'GSK Consumer Healthcare',
        'generic_name': 'Oxymetazoline Hydrochloride Nasal Solution',
        'composition': 'Oxymetazoline HCl (0.05% w/v)',
        'dosage_form': 'SPRAY',
        'strength': '0.05% w/v',
        'pack_size': 'Spray Bottle of 10ml',
        'price': Decimal('112.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 430,
        'rating': Decimal('4.8'),
        'review_count': 1650,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Fast acting nasal decongestant opening blocked nose in 25 seconds for up to 12 hours.',
        'detailed_description': 'Oxymetazoline is a direct sympathomimetic amine that constricts swollen mucosal blood vessels, immediately restoring clear nasal airflow.',
        'directions': '1 spray into each nostril 2 to 3 times daily. Do not use for more than 7 consecutive days.',
        'warnings': 'Prolonged use can lead to rebound rhinitis medicamentosa. For nasal use only.',
        'storage_information': 'Store below 30°C. Protect from heat.',
        'tags': ['nasal spray', 'blocked nose', 'oxymetazoline', 'decongestant']
    },
    {
        'name': 'Solvin Cold Tablet',
        'slug': 'solvin-cold-tablet',
        'sku': 'MED-FEV-009',
        'category_slug': 'fever-cold',
        'brand_name': 'Ipca Laboratories',
        'manufacturer': 'Ipca Laboratories Ltd',
        'generic_name': 'Paracetamol, Phenylephrine and Chlorpheniramine',
        'composition': 'Paracetamol (500mg) + Phenylephrine (10mg) + CPM (2mg)',
        'dosage_form': 'TABLET',
        'strength': 'Combination',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('62.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 360,
        'rating': Decimal('4.6'),
        'review_count': 510,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Comprehensive relief from flu chills, headache, watery eyes, and rhinovirus infection.',
        'detailed_description': 'Effective symptom manager combining an antihistamine, decongestant, and analgesic to treat viral rhinitis.',
        'directions': 'Take 1 tablet every 8 hours after food.',
        'warnings': 'Prescription required. Avoid driving if drowsiness occurs.',
        'storage_information': 'Store in a dry location below 25°C.',
        'tags': ['flu', 'headache', 'rhinitis', 'rx']
    },
    {
        'name': 'Vicks Inhaler Keychain',
        'slug': 'vicks-inhaler-keychain',
        'sku': 'MED-FEV-010',
        'category_slug': 'fever-cold',
        'brand_name': 'Procter & Gamble',
        'manufacturer': 'P&G Hygiene and Health Care Ltd',
        'generic_name': 'Menthol and Camphor Portable Inhaler',
        'composition': 'Menthol (41.54% w/w) + Camphor (41.54% w/w)',
        'dosage_form': 'INHALER',
        'strength': '0.5ml',
        'pack_size': 'Pocket Inhaler Stick',
        'price': Decimal('65.00'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 950,
        'rating': Decimal('4.9'),
        'review_count': 2800,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Pocket-sized aromatic inhaler providing instant soothing sensation for stuffed nostrils.',
        'detailed_description': 'Compact, on-the-go nasal stick with concentrated cooling menthol vapors that open congested airways anywhere, anytime.',
        'directions': 'Insert into nostril and inhale deeply while closing the other nostril.',
        'warnings': 'For individual personal use to prevent infection transmission.',
        'storage_information': 'Tightly recap after every use.',
        'tags': ['inhaler', 'menthol', 'pocket', 'instant relief']
    },
    {
        'name': 'Paracip 650 Tablet',
        'slug': 'paracip-650-tablet',
        'sku': 'MED-FEV-011',
        'category_slug': 'fever-cold',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Paracetamol 650mg Tablets IP',
        'composition': 'Paracetamol (650mg)',
        'dosage_form': 'TABLET',
        'strength': '650mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('22.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 600,
        'rating': Decimal('4.6'),
        'review_count': 640,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Quality high-potency paracetamol for seasonal influenza fever and body ache.',
        'detailed_description': 'Paracip reliably reduces core body temperature during viral fever spikes with minimal gastric side effects.',
        'directions': '1 tablet every 6 hours as needed with water.',
        'warnings': 'Do not consume alcohol while taking paracetamol.',
        'storage_information': 'Store below 25°C protected from moisture.',
        'tags': ['paracetamol', 'fever', 'cipla']
    },
    {
        'name': 'Febrex Plus Syrup',
        'slug': 'febrex-plus-syrup',
        'sku': 'MED-FEV-012',
        'category_slug': 'fever-cold',
        'brand_name': 'Indoco Remedies',
        'manufacturer': 'Indoco Remedies Ltd',
        'generic_name': 'Paracetamol, Phenylephrine and Chlorpheniramine Syrup',
        'composition': 'Each 5ml: Paracetamol (250mg) + Phenylephrine (5mg) + CPM (2mg)',
        'dosage_form': 'SYRUP',
        'strength': '250mg/5mg/2mg per 5ml',
        'pack_size': 'Bottle of 60ml',
        'price': Decimal('84.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 280,
        'rating': Decimal('4.7'),
        'review_count': 310,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Flavored pediatric cold and fever suspension clearing nasal passages and soothing throat irritation.',
        'detailed_description': 'Balanced pediatric formulation with pleasant mixed fruit taste, helping children recover smoothly from colds and fever.',
        'directions': 'Administer using calibrated spoon as per pediatric dosage guide.',
        'warnings': 'Prescription only. May cause drowsiness.',
        'storage_information': 'Store in a cool dry place away from direct light.',
        'tags': ['syrup', 'pediatric', 'cold and fever', 'rx']
    },
    {
        'name': 'Cofsils Cough & Cold Lozenges',
        'slug': 'cofsils-cough-cold-lozenges',
        'sku': 'MED-FEV-013',
        'category_slug': 'fever-cold',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Health Ltd',
        'generic_name': 'Amylmetacresol and Dichlorobenzyl Alcohol Throat Lozenges',
        'composition': 'Amylmetacresol (0.6mg) + Dichlorobenzyl Alcohol (1.2mg)',
        'dosage_form': 'OTHER',
        'strength': 'Ginger Lemon Flavor',
        'pack_size': 'Strip of 10 lozenges',
        'price': Decimal('38.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 650,
        'rating': Decimal('4.8'),
        'review_count': 980,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Antiseptic throat lozenges that eliminate bacteria and numb scratchy raw throat soreness in minutes.',
        'detailed_description': 'Dual antibacterial agents kill throat pathogens while natural ginger-lemon soothing extracts reduce irritating cough reflex.',
        'directions': 'Dissolve 1 lozenge slowly in the mouth every 2 to 3 hours as needed.',
        'warnings': 'Do not chew or swallow whole. Not recommended for children under 6.',
        'storage_information': 'Store below 25°C away from high humidity.',
        'tags': ['lozenges', 'sore throat', 'antibacterial', 'ginger lemon']
    },

    # ---------------- 3. Cough & Respiratory ----------------
    {
        'name': 'Ascoril D Plus Syrup',
        'slug': 'ascoril-d-plus-syrup',
        'sku': 'MED-COU-001',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Glenmark',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Dextromethorphan, Phenylephrine and Chlorpheniramine Syrup',
        'composition': 'Each 5ml: Dextromethorphan HBr (10mg) + Phenylephrine (5mg) + CPM (2mg)',
        'dosage_form': 'SYRUP',
        'strength': '10mg/5mg/2mg per 5ml',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('132.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 420,
        'rating': Decimal('4.8'),
        'review_count': 1350,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Fast dry cough suppressant eliminating tickling throat spasms and nighttime coughing fits.',
        'detailed_description': 'Ascoril D Plus acts centrally on the cough center in the medulla to suppress dry hacking cough while decongesting inflamed upper airways.',
        'directions': 'Take 5ml to 10ml thrice daily, or as advised by a physician.',
        'warnings': 'Prescription medicine. May cause mild sedation. Avoid alcohol while taking.',
        'storage_information': 'Store in a cool dry place protected from sunlight.',
        'tags': ['dry cough', 'dextromethorphan', 'syrup', 'rx']
    },
    {
        'name': 'Benadryl Dry Cough Active Syrup',
        'slug': 'benadryl-dry-cough-active-syrup',
        'sku': 'MED-COU-002',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Johnson & Johnson',
        'manufacturer': 'J&J Consumer India',
        'generic_name': 'Diphenhydramine HCl and Ammonium Chloride Syrup',
        'composition': 'Diphenhydramine HCl (14.08mg) + Ammonium Chloride (138mg)',
        'dosage_form': 'SYRUP',
        'strength': '14mg/138mg per 5ml',
        'pack_size': 'Bottle of 150ml',
        'price': Decimal('145.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 390,
        'rating': Decimal('4.7'),
        'review_count': 1100,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Doctor-endorsed soothing syrup for persistent dry allergy coughs and throat tickle.',
        'detailed_description': 'Diphenhydramine blocks histamine receptors to quiet coughing and soothe raw bronchial passages, helping patients rest comfortably overnight.',
        'directions': 'Adults: 10ml every 4 hours. Children (6-12 yrs): 5ml every 4 hours.',
        'warnings': 'Causes drowsiness. Do not drive or operate machinery after consumption.',
        'storage_information': 'Keep bottle tightly closed below 25°C.',
        'tags': ['benadryl', 'dry cough', 'night cough', 'soothing']
    },
    {
        'name': 'Asthalin Inhaler 100mcg',
        'slug': 'asthalin-inhaler-100mcg',
        'sku': 'MED-COU-003',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Salbutamol Inhalation Aerosol IP',
        'composition': 'Salbutamol (100mcg per actuation)',
        'dosage_form': 'INHALER',
        'strength': '100mcg',
        'pack_size': 'Canister of 200 metered doses',
        'price': Decimal('165.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 520,
        'rating': Decimal('4.9'),
        'review_count': 2400,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Essential quick-relief bronchodilator inhaler for sudden asthma attacks, wheezing, and COPD breathlessness.',
        'detailed_description': 'Asthalin stimulates beta-2 adrenergic receptors in bronchial smooth muscle, producing rapid relaxation within 3 minutes and opening constricted airways.',
        'directions': 'Inhale 1 to 2 puffs during acute bronchospasm. Rinse mouth with water after use.',
        'warnings': 'Strict prescription medicine. Do not exceed recommended dosage. Monitor heart rate.',
        'storage_information': 'Store below 30°C. Protect from freezing and direct sunlight.',
        'tags': ['asthma', 'inhaler', 'salbutamol', 'bronchodilator', 'rx']
    },
    {
        'name': 'Grilinctus BM Syrup',
        'slug': 'grilinctus-bm-syrup',
        'sku': 'MED-COU-004',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Franco-Indian',
        'manufacturer': 'Franco-Indian Pharmaceuticals Ltd',
        'generic_name': 'Terbutaline Sulphate and Bromhexine HCl',
        'composition': 'Each 5ml: Terbutaline (1.25mg) + Bromhexine (4mg)',
        'dosage_form': 'SYRUP',
        'strength': '1.25mg/4mg per 5ml',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('110.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 340,
        'rating': Decimal('4.7'),
        'review_count': 820,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Dual-action bronchodilator and mucolytic syrup for productive wet cough with chest congestion.',
        'detailed_description': 'Bromhexine liquefies tenacious bronchial mucus while Terbutaline dilates airways, facilitating effortless productive coughing.',
        'directions': '10ml three times daily after food, or as directed by a pulmonologist.',
        'warnings': 'Prescription required. May cause minor tremors or palpitations.',
        'storage_information': 'Store in a cool place away from moisture.',
        'tags': ['wet cough', 'mucolytic', 'bronchial', 'rx']
    },
    {
        'name': 'Budecort 200 Inhaler',
        'slug': 'budecort-200-inhaler',
        'sku': 'MED-COU-005',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Budesonide Inhalation Aerosol',
        'composition': 'Budesonide (200mcg per actuation)',
        'dosage_form': 'INHALER',
        'strength': '200mcg',
        'pack_size': 'Canister of 200 metered actuations',
        'price': Decimal('385.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 210,
        'rating': Decimal('4.8'),
        'review_count': 640,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Daily maintenance corticosteroid inhaler controlling airway inflammation in chronic asthma.',
        'detailed_description': 'Budesonide delivers topical anti-inflammatory control to bronchial membranes, significantly reducing bronchial hyperreactivity and exacerbation frequency.',
        'directions': '1 to 2 puffs twice daily. Always rinse mouth thoroughly with water after inhalation to prevent oral thrush.',
        'warnings': 'Prescription only. Not for immediate relief of acute asthma attacks.',
        'storage_information': 'Store below 30°C. Do not puncture container.',
        'tags': ['corticosteroid', 'maintenance', 'budesonide', 'rx']
    },
    {
        'name': 'Montair-LC Tablet',
        'slug': 'montair-lc-tablet',
        'sku': 'MED-COU-006',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Montelukast and Levocetirizine',
        'composition': 'Montelukast Sodium (10mg) + Levocetirizine HCl (5mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg/5mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('235.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 490,
        'rating': Decimal('4.8'),
        'review_count': 1820,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Gold-standard anti-allergic tablet treating allergic rhinitis, pollen asthma, and chronic morning sneezing.',
        'detailed_description': 'Montelukast antagonizes leukotriene D4 receptors to stop airway constriction, while Levocetirizine blocks histamine, providing 24-hour symptom shield.',
        'directions': 'Take 1 tablet once daily at bedtime with or without food.',
        'warnings': 'Prescription required. Monitor for mood changes or vivid dreams.',
        'storage_information': 'Store in original packaging below 25°C.',
        'tags': ['allergy', 'montelukast', 'asthma', 'anti-allergic', 'rx']
    },
    {
        'name': 'Koflet Syrup',
        'slug': 'koflet-syrup',
        'sku': 'MED-COU-007',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Himalaya Wellness',
        'manufacturer': 'The Himalaya Drug Company',
        'generic_name': 'Ayurvedic Honey & Tulsi Cough Formula',
        'composition': 'Madhu (Honey 1.25g) + Tulasi (Holy Basil 25mg) + Yashtimadhu (Licorice 15mg) per 5ml',
        'dosage_form': 'SYRUP',
        'strength': '100ml',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('115.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 450,
        'rating': Decimal('4.6'),
        'review_count': 910,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Non-drowsy ayurvedic cough syrup blending holy basil and pure honey to soothe respiratory tract.',
        'detailed_description': 'Herbal formula that calms the cough reflex, demulcents irritated pharyngeal mucosa, and bolsters local immune defenses without daytime grogginess.',
        'directions': 'Adults: 1 to 2 teaspoonfuls (5-10ml) 3 to 4 times a day.',
        'warnings': 'Safe herbal syrup. Diabetic patients should monitor honey sugar content.',
        'storage_information': 'Shake bottle well before use. Store in a cool dry place.',
        'tags': ['ayurvedic', 'honey', 'tulsi', 'non drowsy', 'herbal']
    },
    {
        'name': 'Duolin Respules',
        'slug': 'duolin-respules',
        'sku': 'MED-COU-008',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Levosalbutamol and Ipratropium Bromide Respules',
        'composition': 'Levosalbutamol (1.25mg) + Ipratropium Bromide (500mcg) per 2.5ml',
        'dosage_form': 'LIQUID',
        'strength': '1.25mg/500mcg',
        'pack_size': 'Pack of 5 respules (2.5ml each)',
        'price': Decimal('145.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 310,
        'rating': Decimal('4.9'),
        'review_count': 560,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Nebulizer liquid respules providing emergency bronchodilation for severe COPD and asthma distress.',
        'detailed_description': 'Combines anticholinergic Ipratropium with selective beta-2 agonist Levosalbutamol for comprehensive large and small airway dilation via jet nebulizer.',
        'directions': 'To be administered via electric jet nebulizer strictly as directed by a doctor.',
        'warnings': 'Rx only. Not for oral consumption or direct injection. Keep away from eyes.',
        'storage_information': 'Store below 25°C. Protect from light.',
        'tags': ['nebulizer', 'copd', 'respule', 'emergency relief', 'rx']
    },
    {
        'name': 'Honitus Herbal Cough Syrup',
        'slug': 'honitus-herbal-cough-syrup',
        'sku': 'MED-COU-009',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Dabur',
        'manufacturer': 'Dabur India Ltd',
        'generic_name': 'Ayurvedic Honey, Mulethi and Tulsi Cough Syrup',
        'composition': 'Honey, Mulethi, Tulsi, Banapsha, Kantkari, Pippali, Sunthi',
        'dosage_form': 'SYRUP',
        'strength': '100ml',
        'pack_size': 'Bottle of 100ml',
        'price': Decimal('110.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 600,
        'rating': Decimal('4.7'),
        'review_count': 1420,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': '100% ayurvedic cough syrup clinically proven to relieve dry and productive cough without sedation.',
        'detailed_description': 'Fortified with five potent botanical herbs and forest honey, Dabur Honitus targets throat tickle, clears phlegm, and eases chest tightness.',
        'directions': '2 teaspoonfuls (10ml) 3 to 4 times a day with lukewarm water.',
        'warnings': 'Herbal proprietary formulation. Keep out of reach of children.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['dabur', 'honitus', 'herbal', 'natural cough']
    },
    {
        'name': 'Mucolite Drop',
        'slug': 'mucolite-drop',
        'sku': 'MED-COU-010',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Dr. Reddy\'s',
        'manufacturer': 'Dr. Reddy\'s Laboratories Ltd',
        'generic_name': 'Ambroxol Hydrochloride Oral Drops',
        'composition': 'Ambroxol HCl (7.5mg per ml)',
        'dosage_form': 'DROPS',
        'strength': '7.5mg/ml',
        'pack_size': 'Dropper Bottle of 15ml',
        'price': Decimal('72.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 210,
        'rating': Decimal('4.8'),
        'review_count': 290,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Pediatric secretolytic drops that thin sticky mucus in infant bronchitis and tracheobronchitis.',
        'detailed_description': 'Ambroxol enhances serous mucus production, promotes pulmonary surfactant synthesis, and activates ciliary clearance to loosen deep chest phlegm.',
        'directions': 'Administer using calibrated dropper strictly as prescribed by the child specialist.',
        'warnings': 'Prescription required. Shake bottle before dispensing.',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['ambroxol', 'pediatric drops', 'mucus clearance', 'rx']
    },
    {
        'name': 'Aerocort Forte Inhaler',
        'slug': 'aerocort-forte-inhaler',
        'sku': 'MED-COU-011',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Cipla',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Beclomethasone Dipropionate and Levosalbutamol Inhaler',
        'composition': 'Beclomethasone (100mcg) + Levosalbutamol (50mcg) per actuation',
        'dosage_form': 'INHALER',
        'strength': '100mcg/50mcg',
        'pack_size': 'Canister of 200 metered actuations',
        'price': Decimal('320.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 180,
        'rating': Decimal('4.7'),
        'review_count': 380,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Combined bronchodilator and anti-inflammatory inhaler for chronic reversible airway obstruction.',
        'detailed_description': 'Provides round-the-clock dual action by decreasing mucosal edema with Beclomethasone and relaxing bronchial muscles with Levosalbutamol.',
        'directions': '2 puffs twice daily. Always rinse mouth thoroughly after use.',
        'warnings': 'Prescription only. Do not stop abruptly without medical advice.',
        'storage_information': 'Store below 30°C. Protect from frost.',
        'tags': ['inhaler', 'beclomethasone', 'levosalbutamol', 'rx']
    },
    {
        'name': 'Strepsils Honey & Lemon Lozenges',
        'slug': 'strepsils-honey-lemon-lozenges',
        'sku': 'MED-COU-012',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Reckitt Benckiser',
        'manufacturer': 'Reckitt Benckiser Healthcare India',
        'generic_name': 'Amylmetacresol & Dichlorobenzyl Alcohol Lozenges',
        'composition': '2,4-Dichlorobenzyl Alcohol (1.2mg) + Amylmetacresol (0.6mg)',
        'dosage_form': 'OTHER',
        'strength': 'Honey Lemon',
        'pack_size': 'Blister pack of 8 lozenges',
        'price': Decimal('35.00'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 800,
        'rating': Decimal('4.9'),
        'review_count': 2200,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Rapid soothing lozenges providing warm honey relief from painful raw throat and early coughing.',
        'detailed_description': 'Formulated with two active antiseptics that destroy bacteria causing sore throat and upper respiratory irritation.',
        'directions': 'Dissolve 1 lozenge slowly in the mouth every 2 hours.',
        'warnings': 'Not suitable for children below 6 years. Do not exceed 8 lozenges in 24 hours.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['strepsils', 'sore throat', 'honey lemon', 'lozenges']
    },
    {
        'name': 'Bresol Tablets',
        'slug': 'bresol-tablets',
        'sku': 'MED-COU-013',
        'category_slug': 'cough-respiratory',
        'brand_name': 'Himalaya Wellness',
        'manufacturer': 'The Himalaya Drug Company',
        'generic_name': 'Ayurvedic Anti-Allergic Respiratory Formula',
        'composition': 'Haridra (Curcuma longa 100.5mg) + Tulasi (50mg) + Vasaka (50mg)',
        'dosage_form': 'TABLET',
        'strength': 'Herbal formulation',
        'pack_size': 'Bottle of 60 tablets',
        'price': Decimal('195.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 260,
        'rating': Decimal('4.6'),
        'review_count': 410,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Herbal respiratory support tablet alleviating chronic allergic bronchitis, pollen allergies, and sinus congestion.',
        'detailed_description': 'Vasaka and Haridra exhibit natural antihistaminic and mast-cell stabilizing properties, fostering free lung airflow and resisting seasonal allergens.',
        'directions': '2 tablets twice daily with water before meals.',
        'warnings': 'Safe ayurvedic product. Consult physician during pregnancy.',
        'storage_information': 'Store in a cool dry place away from moisture.',
        'tags': ['bresol', 'ayurvedic', 'asthma support', 'allergy']
    },

    # ---------------- 4. Digestive Health ----------------
    {
        'name': 'Pan 40 Tablet',
        'slug': 'pan-40-tablet',
        'sku': 'MED-DIG-001',
        'category_slug': 'digestive-health',
        'brand_name': 'Alkem Laboratories',
        'manufacturer': 'Alkem Laboratories Ltd',
        'generic_name': 'Pantoprazole Gastro-Resistant Tablets IP 40mg',
        'composition': 'Pantoprazole Sodium (40mg)',
        'dosage_form': 'TABLET',
        'strength': '40mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('162.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 750,
        'rating': Decimal('4.8'),
        'review_count': 2300,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Leading proton pump inhibitor for severe acidity, GERD, heartburn, and stomach ulcers.',
        'detailed_description': 'Pan 40 irreversibly blocks H+/K+ ATPase enzyme systems in gastric parietal cells, shutting down excess acid secretion for sustained 24-hour digestive comfort.',
        'directions': 'Take 1 tablet in the morning 30 minutes before breakfast with a glass of water. Swallow whole.',
        'warnings': 'Prescription required. Do not crush or chew the gastro-resistant coating.',
        'storage_information': 'Store below 25°C away from humidity.',
        'tags': ['acidity', 'pantoprazole', 'gerd', 'heartburn', 'rx']
    },
    {
        'name': 'Gelusil MPS Antacid Liquid',
        'slug': 'gelusil-mps-antacid-liquid',
        'sku': 'MED-DIG-002',
        'category_slug': 'digestive-health',
        'brand_name': 'Pfizer India',
        'manufacturer': 'Pfizer Products India Pvt Ltd',
        'generic_name': 'Aluminium Hydroxide, Magnesium Hydroxide and Simethicone',
        'composition': 'Magnesium Hydroxide (250mg) + Aluminium Hydroxide (250mg) + Simethicone (50mg) per 5ml',
        'dosage_form': 'LIQUID',
        'strength': 'Mint Flavor 200ml',
        'pack_size': 'Bottle of 200ml',
        'price': Decimal('138.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 580,
        'rating': Decimal('4.8'),
        'review_count': 1650,
        'prescription_required': False,
        'featured': True,
        'trending': False,
        'bestseller': True,
        'short_description': 'Fast-acting liquid antacid providing instant neutralising relief from burning heartburn and trapped gas.',
        'detailed_description': 'Balanced mineral hydroxide suspension neutralizes stomach hydrochloric acid immediately, while activated Simethicone coalesces trapped gas bubbles for quick debloating.',
        'directions': '1 to 2 teaspoonfuls (5-10ml) after meals and at bedtime.',
        'warnings': 'Shake bottle well. Patients with kidney dysfunction should consult a physician.',
        'storage_information': 'Store below 30°C. Do not freeze.',
        'tags': ['gelusil', 'antacid', 'heartburn', 'gas relief', 'otc']
    },
    {
        'name': 'Omez 20 Capsule',
        'slug': 'omez-20-capsule',
        'sku': 'MED-DIG-003',
        'category_slug': 'digestive-health',
        'brand_name': 'Dr. Reddy\'s',
        'manufacturer': 'Dr. Reddy\'s Laboratories Ltd',
        'generic_name': 'Omeprazole Gastro-Resistant Capsules IP 20mg',
        'composition': 'Omeprazole (20mg enteric-coated pellets)',
        'dosage_form': 'CAPSULE',
        'strength': '20mg',
        'pack_size': 'Strip of 20 capsules',
        'price': Decimal('118.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 620,
        'rating': Decimal('4.8'),
        'review_count': 1950,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Benchmark antacid capsule for healing duodenal ulcers, erosive esophagitis, and persistent acid reflux.',
        'detailed_description': 'Omeprazole pellets release post-gastric passage to inhibit basal and stimulated gastric acid production, aiding mucosal ulcer healing.',
        'directions': 'Take 1 capsule daily on an empty stomach in the morning.',
        'warnings': 'Prescription medicine. Swallow whole; do not chew or empty pellet contents.',
        'storage_information': 'Store below 25°C protected from light and moisture.',
        'tags': ['omeprazole', 'ulcer', 'acid reflux', 'rx']
    },
    {
        'name': 'Eno Fruit Salt Regular',
        'slug': 'eno-fruit-salt-regular',
        'sku': 'MED-DIG-004',
        'category_slug': 'digestive-health',
        'brand_name': 'GlaxoSmithKline',
        'manufacturer': 'GSK Consumer Healthcare',
        'generic_name': 'Svarjiksara & Nimbukamlam Effervescent Antacid',
        'composition': 'Svarjiksara (Sodium Bicarbonate 2.91g) + Nimbukamlam (Citric Acid 2.04g)',
        'dosage_form': 'POWDER',
        'strength': '100g Bottle',
        'pack_size': 'Bottle of 100g',
        'price': Decimal('160.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 820,
        'rating': Decimal('4.9'),
        'review_count': 3400,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Instant effervescent powder neutralizing stomach acid in just 6 seconds.',
        'detailed_description': 'Upon dissolution in water, Eno releases carbon dioxide and sodium citrate, buffering harsh stomach acids and delivering immediate chest and stomach relief.',
        'directions': 'Dissolve 1 level teaspoon (5g) in a glass of water (150ml). Drink immediately as effervescence occurs.',
        'warnings': 'Do not take more than 2 doses a day. High sodium content; caution in hypertensive patients.',
        'storage_information': 'Keep bottle tightly sealed to prevent atmospheric moisture absorption.',
        'tags': ['eno', 'effervescent', 'fast acidity', 'instant relief']
    },
    {
        'name': 'Sporlac DS Tablet',
        'slug': 'sporlac-ds-tablet',
        'sku': 'MED-DIG-005',
        'category_slug': 'digestive-health',
        'brand_name': 'Sanzyme',
        'manufacturer': 'Sanzyme Ltd',
        'generic_name': 'Lactic Acid Bacillus (Bacillus coagulans) Tablets',
        'composition': 'Lactic Acid Bacillus spores (120 million viable spores)',
        'dosage_form': 'TABLET',
        'strength': '120 Million Spores',
        'pack_size': 'Strip of 20 tablets',
        'price': Decimal('156.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 410,
        'rating': Decimal('4.7'),
        'review_count': 640,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Potent spore-forming probiotic restoring gut microflora after antibiotic courses and acute diarrhea.',
        'detailed_description': 'Resistant to harsh stomach acidity, Bacillus coagulans germinates in the intestine to synthesize bacteriocins, normalize bowel motility, and re-establish healthy microbiome colonies.',
        'directions': '1 tablet twice daily with water after meals.',
        'warnings': 'Safe digestive probiotic. Keep blister dry.',
        'storage_information': 'Store in a cool dry place below 25°C.',
        'tags': ['probiotic', 'sporlac', 'gut health', 'antibiotic recovery']
    },
    {
        'name': 'Cremaffin Plus Emulsion',
        'slug': 'cremaffin-plus-emulsion',
        'sku': 'MED-DIG-006',
        'category_slug': 'digestive-health',
        'brand_name': 'Abbott India',
        'manufacturer': 'Abbott Healthcare Pvt Ltd',
        'generic_name': 'Liquid Paraffin, Milk of Magnesia and Sodium Picosulfate',
        'composition': 'Liquid Paraffin (1.25ml) + Milk of Magnesia (3.75ml) + Sodium Picosulfate (3.33mg) per 5ml',
        'dosage_form': 'LIQUID',
        'strength': 'Mint Flavor 225ml',
        'pack_size': 'Bottle of 225ml',
        'price': Decimal('295.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 350,
        'rating': Decimal('4.8'),
        'review_count': 920,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Gentle triple-action bowel regulator for painless relief from chronic constipation and piles discomfort.',
        'detailed_description': 'Milk of magnesia draws water into the colon, Sodium picosulfate stimulates gentle peristalsis, and Liquid paraffin lubricates the stool for strain-free defecation.',
        'directions': 'Adults: 15ml to 22.5ml at bedtime with half a glass of water.',
        'warnings': 'Do not use continuously for prolonged periods. Shake well before use.',
        'storage_information': 'Store at room temperature below 30°C.',
        'tags': ['cremaffin', 'constipation', 'laxative', 'piles relief']
    },
    {
        'name': 'Digene Acidity & Gas Relief Tablets',
        'slug': 'digene-acidity-gas-relief-tablets',
        'sku': 'MED-DIG-007',
        'category_slug': 'digestive-health',
        'brand_name': 'Abbott India',
        'manufacturer': 'Abbott India Ltd',
        'generic_name': 'Dried Aluminium Hydroxide, Magnesium Aluminium Silicate, Magnesium Hydroxide and Simethicone',
        'composition': 'Aluminium Hydroxide (300mg) + Magnesium Hydroxide (25mg) + Simethicone (25mg)',
        'dosage_form': 'TABLET',
        'strength': 'Mixed Fruit Flavor',
        'pack_size': 'Strip of 15 chewable tablets',
        'price': Decimal('25.50'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 880,
        'rating': Decimal('4.8'),
        'review_count': 2200,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Pocket chewable antacid tablet for quick portable relief from sour belching and bloating.',
        'detailed_description': 'Chewable formulation coats the esophageal and gastric lining, neutralizing excess acid pockets and dissipating gas on contact.',
        'directions': 'Chew 1 to 2 tablets thoroughly after meals or when symptoms flare up.',
        'warnings': 'Chew thoroughly before swallowing. Not intended for continuous long-term use.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['digene', 'chewable', 'acidity', 'otc']
    },
    {
        'name': 'Pudin Hara Active Liquid Pearls',
        'slug': 'pudin-hara-active-liquid-pearls',
        'sku': 'MED-DIG-008',
        'category_slug': 'digestive-health',
        'brand_name': 'Dabur',
        'manufacturer': 'Dabur India Ltd',
        'generic_name': 'Mentha Piperita and Mentha Spicata Herbal Pearls',
        'composition': 'Pudina Satva (Mentha oil 0.03ml per pearl)',
        'dosage_form': 'CAPSULE',
        'strength': 'Pearls',
        'pack_size': 'Strip of 10 pearls',
        'price': Decimal('32.00'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 900,
        'rating': Decimal('4.9'),
        'review_count': 3100,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Natural herbal mint capsules that cool down stomach fires, easing bloating, cramps, and gas.',
        'detailed_description': 'Concentrated mint oils relax gastrointestinal smooth muscle fibers and exert carminative action, expelling stubborn flatulence naturally.',
        'directions': '1 pearl swallowed whole with a glass of cool water after heavy meals.',
        'warnings': 'Do not chew or puncture pearls in mouth. Avoid in infant age groups.',
        'storage_information': 'Store in a cool dry place below 25°C.',
        'tags': ['pudin hara', 'mint', 'bloating', 'gas', 'ayurvedic']
    },
    {
        'name': 'Razo 20 Tablet',
        'slug': 'razo-20-tablet',
        'sku': 'MED-DIG-009',
        'category_slug': 'digestive-health',
        'brand_name': 'Dr. Reddy\'s',
        'manufacturer': 'Dr. Reddy\'s Laboratories Ltd',
        'generic_name': 'Rabeprazole Sodium Gastro-Resistant Tablets IP 20mg',
        'composition': 'Rabeprazole Sodium (20mg)',
        'dosage_form': 'TABLET',
        'strength': '20mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('210.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 430,
        'rating': Decimal('4.8'),
        'review_count': 1120,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'High-efficacy rabeprazole tablet delivering faster acid suppression for erosive esophagitis.',
        'detailed_description': 'Rabeprazole exhibits rapid activation at neutral-to-acidic pH, achieving faster inhibition of acid pumps compared to legacy PPI molecules.',
        'directions': 'Take 1 tablet in the morning 30 minutes before food.',
        'warnings': 'Prescription required. Do not break or chew the tablet.',
        'storage_information': 'Store below 25°C away from direct moisture.',
        'tags': ['rabeprazole', 'gerd', 'stomach acid', 'rx']
    },
    {
        'name': 'Electral ORS Powder',
        'slug': 'electral-ors-powder',
        'sku': 'MED-DIG-010',
        'category_slug': 'digestive-health',
        'brand_name': 'FDC Limited',
        'manufacturer': 'FDC Ltd',
        'generic_name': 'Oral Rehydration Salts WHO Formula',
        'composition': 'Sodium Chloride (2.6g) + Potassium Chloride (1.5g) + Sodium Citrate (2.9g) + Dextrose Anhydrous (13.5g)',
        'dosage_form': 'POWDER',
        'strength': '21.8g Sachet',
        'pack_size': 'Sachet of 21.8g for 1 Liter',
        'price': Decimal('22.50'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 1200,
        'rating': Decimal('4.9'),
        'review_count': 4100,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'WHO-recommended rehydration formula restoring essential electrolytes lost during diarrhea, vomiting, and heat exhaustion.',
        'detailed_description': 'Optimized sodium-to-glucose co-transport formula enables rapid fluid and electrolyte absorption across the intestinal lumen, preventing life-threatening dehydration.',
        'directions': 'Dissolve entire 21.8g sachet in 1 liter of boiled and cooled drinking water. Consume within 24 hours.',
        'warnings': 'Do not boil prepared solution. Discard leftover solution after 24 hours.',
        'storage_information': 'Store sachet in a dry place away from moisture.',
        'tags': ['ors', 'electral', 'dehydration', 'diarrhea', 'who formula']
    },
    {
        'name': 'Dulcoflex 5mg Tablet',
        'slug': 'dulcoflex-5mg-tablet',
        'sku': 'MED-DIG-011',
        'category_slug': 'digestive-health',
        'brand_name': 'Sanofi India',
        'manufacturer': 'Sanofi India Ltd',
        'generic_name': 'Bisacodyl Gastro-Resistant Tablets IP 5mg',
        'composition': 'Bisacodyl (5mg)',
        'dosage_form': 'TABLET',
        'strength': '5mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('16.00'),
        'discount_percent': Decimal('5.00'),
        'stock_quantity': 720,
        'rating': Decimal('4.6'),
        'review_count': 1240,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Predictable overnight stimulant laxative triggering morning bowel movements.',
        'detailed_description': 'Bisacodyl directly stimulates sensory nerve endings in the colonic wall, accelerating transit and providing reliable bowel clearance in 6 to 12 hours.',
        'directions': 'Adults: 1 to 2 tablets at bedtime with water.',
        'warnings': 'Do not take with antacids or milk within 1 hour. Swallow whole.',
        'storage_information': 'Store below 25°C in dry conditions.',
        'tags': ['dulcoflex', 'bisacodyl', 'constipation', 'laxative']
    },
    {
        'name': 'Isabgol Husk Powder',
        'slug': 'isabgol-husk-powder',
        'sku': 'MED-DIG-012',
        'category_slug': 'digestive-health',
        'brand_name': 'Baidyanath',
        'manufacturer': 'Shree Baidyanath Ayurved Bhavan Pvt Ltd',
        'generic_name': 'Pure Plantago Ovata (Psyllium Husk) Fiber',
        'composition': '100% Pure Psyllium Husk (Isabgol)',
        'dosage_form': 'POWDER',
        'strength': '100g Container',
        'pack_size': 'Tub of 100g',
        'price': Decimal('155.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 450,
        'rating': Decimal('4.8'),
        'review_count': 1100,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Natural soluble dietary bulk-forming fiber promoting smooth bowel movements and healthy cholesterol.',
        'detailed_description': 'Natural mucilage absorbs water in the gastrointestinal tract, forming an emollient gel that gently expands bowel mass and facilitates regular transit.',
        'directions': 'Mix 1 to 2 tablespoons in a glass of water, milk, or curd. Drink immediately followed by another glass of water.',
        'warnings': 'Always take with adequate water to prevent choking.',
        'storage_information': 'Keep container tightly closed in a dry place.',
        'tags': ['isabgol', 'psyllium', 'fiber', 'natural laxative']
    },
    {
        'name': 'Eldoper 2mg Capsule',
        'slug': 'eldoper-2mg-capsule',
        'sku': 'MED-DIG-013',
        'category_slug': 'digestive-health',
        'brand_name': 'Micro Labs',
        'manufacturer': 'Micro Labs Ltd',
        'generic_name': 'Loperamide Hydrochloride Capsules IP 2mg',
        'composition': 'Loperamide HCl (2mg)',
        'dosage_form': 'CAPSULE',
        'strength': '2mg',
        'pack_size': 'Strip of 10 capsules',
        'price': Decimal('28.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 510,
        'rating': Decimal('4.7'),
        'review_count': 820,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Fast anti-motility medicine stopping acute non-infectious loose motions and traveler\'s diarrhea.',
        'detailed_description': 'Loperamide slows down circular and longitudinal intestinal peristalsis, prolonging water and electrolyte reabsorption and firming stool consistency.',
        'directions': 'Initial dose of 2 capsules, followed by 1 capsule after each unformed stool. Maximum 8 capsules daily.',
        'warnings': 'Prescription only. Do not use in bacterial dysentery with blood in stool or high fever.',
        'storage_information': 'Store below 30°C in dry conditions.',
        'tags': ['loperamide', 'diarrhea', 'loose motions', 'rx']
    },

    # ---------------- 5. Diabetes Care ----------------
    {
        'name': 'Accu-Chek Active Test Strips 50s',
        'slug': 'accu-chek-active-test-strips-50s',
        'sku': 'MED-DIA-001',
        'category_slug': 'diabetes-care',
        'brand_name': 'Roche Diabetes Care',
        'manufacturer': 'Roche Diagnostics India',
        'generic_name': 'Blood Glucose Monitoring Biosensor Strips',
        'composition': 'Mutant glucose dehydrogenase (FAD-dependent) biosensor',
        'dosage_form': 'STRIP',
        'strength': '50 Test Strips',
        'pack_size': 'Box of 50 strips',
        'price': Decimal('1125.00'),
        'discount_percent': Decimal('20.00'),
        'stock_quantity': 350,
        'rating': Decimal('4.9'),
        'review_count': 3400,
        'prescription_required': False,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'India\'s standard accurate self-monitoring blood sugar test strips with visual double-check color bar.',
        'detailed_description': 'High-precision capillary enzyme test strips giving laboratory-standard blood sugar readings in 5 seconds with tiny 1-2 microliter sample requirement.',
        'directions': 'Insert strip into Accu-Chek Active meter, apply tiny blood droplet to test pad, view reading in 5 seconds.',
        'warnings': 'Close test strip container immediately after removing a strip. Do not use expired strips.',
        'storage_information': 'Store between 2°C and 30°C in original container.',
        'tags': ['accu-chek', 'diabetes', 'glucometer strips', 'blood sugar']
    },
    {
        'name': 'Glycomet-GP 1 Tablet',
        'slug': 'glycomet-gp-1-tablet',
        'sku': 'MED-DIA-002',
        'category_slug': 'diabetes-care',
        'brand_name': 'USV Private Limited',
        'manufacturer': 'USV Pvt Ltd',
        'generic_name': 'Glimepiride and Metformin Sustained Release',
        'composition': 'Glimepiride (1mg) + Metformin HCl (SR 500mg)',
        'dosage_form': 'TABLET',
        'strength': '1mg/500mg SR',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('142.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 520,
        'rating': Decimal('4.8'),
        'review_count': 1850,
        'prescription_required': True,
        'featured': True,
        'trending': True,
        'bestseller': True,
        'short_description': 'Dual oral anti-diabetic agent managing elevated HbA1c in type-2 diabetes mellitus.',
        'detailed_description': 'Glimepiride stimulates pancreatic beta-cell insulin secretion, while Metformin SR enhances peripheral tissue insulin sensitivity and reduces hepatic glucose output.',
        'directions': 'Take 1 tablet once daily with the main breakfast meal.',
        'warnings': 'Strict prescription medicine. Watch for signs of hypoglycemia (dizziness, cold sweats).',
        'storage_information': 'Store below 25°C away from direct sunlight.',
        'tags': ['metformin', 'glimepiride', 'diabetes', 'type 2', 'rx']
    },
    {
        'name': 'Januvia 100mg Tablet',
        'slug': 'januvia-100mg-tablet',
        'sku': 'MED-DIA-003',
        'category_slug': 'diabetes-care',
        'brand_name': 'MSD Pharmaceuticals',
        'manufacturer': 'Merck Sharp & Dohme Corp / MSD India',
        'generic_name': 'Sitagliptin Phosphate Tablets IP 100mg',
        'composition': 'Sitagliptin Phosphate Monohydrate (100mg)',
        'dosage_form': 'TABLET',
        'strength': '100mg',
        'pack_size': 'Strip of 14 tablets',
        'price': Decimal('640.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 210,
        'rating': Decimal('4.9'),
        'review_count': 780,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Advanced DPP-4 inhibitor providing glucose-dependent insulin release with minimal risk of hypoglycemia.',
        'detailed_description': 'Januvia slows inactivation of incretin hormones (GLP-1 and GIP), naturally increasing insulin synthesis and lowering glucagon levels postprandially.',
        'directions': 'Take 1 tablet once daily with or without meals.',
        'warnings': 'Prescription required. Monitor renal function periodically.',
        'storage_information': 'Store below 30°C in a dry place.',
        'tags': ['sitagliptin', 'dpp4', 'type 2 diabetes', 'rx']
    },
    {
        'name': 'OneTouch Select Plus Test Strips 50s',
        'slug': 'onetouch-select-plus-test-strips-50s',
        'sku': 'MED-DIA-004',
        'category_slug': 'diabetes-care',
        'brand_name': 'LifeScan',
        'manufacturer': 'LifeScan Medical Devices India',
        'generic_name': 'In Vitro Diagnostic Blood Glucose Test Strips',
        'composition': 'Flavin-adenine dinucleotide glucose dehydrogenase (FAD-GDH)',
        'dosage_form': 'STRIP',
        'strength': '50 Test Strips',
        'pack_size': 'Vial of 50 strips',
        'price': Decimal('1180.00'),
        'discount_percent': Decimal('22.00'),
        'stock_quantity': 290,
        'rating': Decimal('4.8'),
        'review_count': 1920,
        'prescription_required': False,
        'featured': False,
        'trending': True,
        'bestseller': True,
        'short_description': 'Accurate 5-second test strips compatible with OneTouch Select Plus ColorSure meters.',
        'detailed_description': 'Automatic hematocrit correction algorithms ensure reliable glycemic tracking across broad ambient temperature ranges.',
        'directions': 'Insert strip, touch tiny blood drop to channel until confirmation window fills.',
        'warnings': 'Do not use bent or damaged strips. Keep vial cap tightly closed.',
        'storage_information': 'Store between 5°C and 30°C.',
        'tags': ['onetouch', 'glucose strips', 'diabetes monitor']
    },
    {
        'name': 'Galvus Met 50mg/500mg Tablet',
        'slug': 'galvus-met-50-500-tablet',
        'sku': 'MED-DIA-005',
        'category_slug': 'diabetes-care',
        'brand_name': 'Novartis India',
        'manufacturer': 'Novartis Healthcare Pvt Ltd',
        'generic_name': 'Vildagliptin and Metformin HCl Tablets',
        'composition': 'Vildagliptin (50mg) + Metformin HCl (500mg)',
        'dosage_form': 'TABLET',
        'strength': '50mg/500mg',
        'pack_size': 'Strip of 15 tablets',
        'price': Decimal('380.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 340,
        'rating': Decimal('4.8'),
        'review_count': 890,
        'prescription_required': True,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Dual incretin-sensitizer therapy providing comprehensive glycemic control in adults with type-2 diabetes.',
        'detailed_description': 'Vildagliptin boosts beta-cell responsiveness while Metformin prevents liver gluconeogenesis without causing weight gain.',
        'directions': 'Take 1 tablet twice daily with meals to avoid gastrointestinal discomfort.',
        'warnings': 'Strict prescription required. Liver function tests recommended prior to therapy.',
        'storage_information': 'Store protected from heat and moisture below 25°C.',
        'tags': ['vildagliptin', 'metformin', 'diabetes', 'novartis', 'rx']
    },
    {
        'name': 'Karela Jamun Juice Diabetic Care',
        'slug': 'karela-jamun-juice-diabetic-care',
        'sku': 'MED-DIA-006',
        'category_slug': 'diabetes-care',
        'brand_name': 'Baidyanath',
        'manufacturer': 'Shree Baidyanath Ayurved Bhavan Pvt Ltd',
        'generic_name': 'Pure Ayurvedic Bitter Gourd & Indian Blackberry Juice',
        'composition': 'Karela Extract (50%) + Jamun Seed Extract (49.8%)',
        'dosage_form': 'LIQUID',
        'strength': '1000ml',
        'pack_size': 'Bottle of 1000ml',
        'price': Decimal('290.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 480,
        'rating': Decimal('4.6'),
        'review_count': 1140,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Natural herbal botanical juice supporting healthy fasting blood sugar and pancreatic vitality.',
        'detailed_description': 'Rich in polypeptide-p and charantin, Karela and Jamun work synergistically to enhance cellular glucose uptake and purify blood naturally.',
        'directions': 'Dilute 30ml in a glass of water and drink on an empty stomach in the morning.',
        'warnings': 'Natural herbal supplement. Monitor sugar levels if taken alongside prescription anti-diabetics.',
        'storage_information': 'Refrigerate after opening and consume within 30 days.',
        'tags': ['karela jamun', 'ayurvedic', 'natural blood sugar', 'juice']
    },
    {
        'name': 'Jardiance 10mg Tablet',
        'slug': 'jardiance-10mg-tablet',
        'sku': 'MED-DIA-007',
        'category_slug': 'diabetes-care',
        'brand_name': 'Boehringer Ingelheim',
        'manufacturer': 'Boehringer Ingelheim India Pvt Ltd',
        'generic_name': 'Empagliflozin Tablets 10mg',
        'composition': 'Empagliflozin (10mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg',
        'pack_size': 'Strip of 10 tablets',
        'price': Decimal('520.00'),
        'discount_percent': Decimal('12.00'),
        'stock_quantity': 190,
        'rating': Decimal('4.9'),
        'review_count': 610,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Breakthrough SGLT2 inhibitor removing excess sugar via urine while providing proven heart and kidney protection.',
        'detailed_description': 'Empagliflozin blocks SGLT2 co-transporters in the proximal renal tubules, discharging excess blood glucose through the urinary tract and reducing arterial stiffness.',
        'directions': 'Take 1 tablet once daily in the morning with plenty of water.',
        'warnings': 'Rx required. Maintain proper hydration and personal hygiene to prevent urinary tract infections.',
        'storage_information': 'Store below 25°C in original packaging.',
        'tags': ['empagliflozin', 'sglt2', 'cardio protection', 'rx']
    },
    {
        'name': 'BD Ultra-Fine Insulin Pen Needles 4mm',
        'slug': 'bd-ultra-fine-insulin-pen-needles-4mm',
        'sku': 'MED-DIA-008',
        'category_slug': 'diabetes-care',
        'brand_name': 'Becton Dickinson',
        'manufacturer': 'Becton Dickinson India Pvt Ltd',
        'generic_name': 'PentaPoint Extra Thin Wall Pen Needles 32G',
        'composition': 'Surgical grade stainless steel with silicone lubrication',
        'dosage_form': 'DEVICE',
        'strength': '32G 4mm',
        'pack_size': 'Box of 100 pen needles',
        'price': Decimal('1650.00'),
        'discount_percent': Decimal('18.00'),
        'stock_quantity': 240,
        'rating': Decimal('4.9'),
        'review_count': 1480,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Ultra-short 4mm insulin pen needles delivering virtually painless subcutaneous insulin delivery.',
        'detailed_description': '5-bevel PentaPoint comfort needle technology slides effortlessly into the skin, preventing painful intramuscular insulin injections.',
        'directions': 'Screw needle securely onto insulin pen. Use a fresh needle for each injection.',
        'warnings': 'Single use only. Dispose in a puncture-proof sharps bin.',
        'storage_information': 'Store at clean room temperature.',
        'tags': ['insulin needle', 'bd needles', 'painless injection', 'diabetes']
    },
    {
        'name': 'Diabecon DS Tablet',
        'slug': 'diabecon-ds-tablet',
        'sku': 'MED-DIA-009',
        'category_slug': 'diabetes-care',
        'brand_name': 'Himalaya Wellness',
        'manufacturer': 'The Himalaya Drug Company',
        'generic_name': 'Ayurvedic Glycemic Support Phytomedicine',
        'composition': 'Meshashringi (Gymnema sylvestre 60mg) + Pitasara (40mg) + Yashtimadhu (40mg)',
        'dosage_form': 'TABLET',
        'strength': 'Double Strength',
        'pack_size': 'Bottle of 60 tablets',
        'price': Decimal('225.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 380,
        'rating': Decimal('4.7'),
        'review_count': 820,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Herbal double-strength formulation helping regenerate beta cells and reduce sugar cravings.',
        'detailed_description': 'Gymnema sylvestre (sugar destroyer) suppresses taste sensitivity to sweets while botanical antioxidants safeguard peripheral nerves from advanced glycation.',
        'directions': '1 tablet twice daily 30 minutes before meals.',
        'warnings': 'Complimentary herbal product. Do not discontinue physician-prescribed medications.',
        'storage_information': 'Store in a cool dry place.',
        'tags': ['diabecon', 'himalaya', 'sugar cravings', 'herbal diabetes']
    },
    {
        'name': 'Diabexy Sugar Free Sweetener',
        'slug': 'diabexy-sugar-free-sweetener',
        'sku': 'MED-DIA-010',
        'category_slug': 'diabetes-care',
        'brand_name': 'NutroActive',
        'manufacturer': 'NutroActive Industries',
        'generic_name': 'Zero Glycemic Index Fructooligosaccharide & Stevia',
        'composition': 'Fructooligosaccharide, Stevia Extract, Isomalt',
        'dosage_form': 'POWDER',
        'strength': '200g Jar',
        'pack_size': 'Jar of 200g',
        'price': Decimal('360.00'),
        'discount_percent': Decimal('10.00'),
        'stock_quantity': 290,
        'rating': Decimal('4.6'),
        'review_count': 510,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': '100% natural Zero Glycemic index prebiotic sweetener taste-identical to regular table sugar.',
        'detailed_description': 'Zero calorie natural blend that does not spike insulin or glucose levels, ideal for tea, coffee, baking, and diabetic meal plans.',
        'directions': 'Use 1 scoop (approx. 1g) to match the sweetness of 1 teaspoon of table sugar.',
        'warnings': 'Safe for diabetics and keto followers.',
        'storage_information': 'Store in a cool dry place. Keep container tightly closed.',
        'tags': ['sugar free', 'zero gi', 'stevia', 'diabetic sweetener']
    },
    {
        'name': 'Glucon-D Instant Energy Tangy Orange',
        'slug': 'glucon-d-instant-energy-orange',
        'sku': 'MED-DIA-011',
        'category_slug': 'diabetes-care',
        'brand_name': 'Zydus Wellness',
        'manufacturer': 'Zydus Wellness Products Ltd',
        'generic_name': 'Glucose-D with Vitamin C and Calcium',
        'composition': 'Dextrose Monohydrate (99.4%) + Vitamin C (50mg) + Calcium',
        'dosage_form': 'POWDER',
        'strength': 'Orange 500g',
        'pack_size': 'Carton of 500g',
        'price': Decimal('165.00'),
        'discount_percent': Decimal('8.00'),
        'stock_quantity': 650,
        'rating': Decimal('4.8'),
        'review_count': 2800,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': True,
        'short_description': 'Emergency fast-absorbing glucose for immediate reversal of diabetic hypoglycemia episodes.',
        'detailed_description': 'Pure dextrose enters bloodstream within 2 minutes, critical for diabetic first-aid rescue during sudden hypoglycemic insulin shocks.',
        'directions': 'In hypoglycemia: mix 3 to 4 teaspoons in half glass of water and drink immediately.',
        'warnings': 'Essential emergency diabetic rescue item. For normal usage, monitor caloric intake.',
        'storage_information': 'Store in an airtight container in a dry pantry.',
        'tags': ['glucose', 'hypoglycemia rescue', 'first aid', 'energy']
    },
    {
        'name': 'Footmender Diabetic Foot Cream',
        'slug': 'footmender-diabetic-foot-cream',
        'sku': 'MED-DIA-012',
        'category_slug': 'diabetes-care',
        'brand_name': 'Dr. Morepen',
        'manufacturer': 'Morepen Laboratories Ltd',
        'generic_name': 'Urea, Lactic Acid and Tea Tree Oil Foot Cream',
        'composition': 'Urea (10% w/w) + Lactic Acid (5% w/w) + Tea Tree Oil (1% w/w)',
        'dosage_form': 'CREAM',
        'strength': '10% Urea',
        'pack_size': 'Tube of 100g',
        'price': Decimal('285.00'),
        'discount_percent': Decimal('15.00'),
        'stock_quantity': 220,
        'rating': Decimal('4.8'),
        'review_count': 440,
        'prescription_required': False,
        'featured': False,
        'trending': False,
        'bestseller': False,
        'short_description': 'Deep hydrating clinical cream preventing cracked heels, xerosis, and ulcer risks in diabetic feet.',
        'detailed_description': 'Formulated with 10% Urea to gently dissolve rough hyperkeratotic skin and Tea Tree oil to prevent microbial colonization in neuropathic diabetic feet.',
        'directions': 'Wash feet with mild soap, pat completely dry, and apply generously twice daily. Do not apply between toes.',
        'warnings': 'Do not apply directly into open diabetic ulcers or bleeding lesions.',
        'storage_information': 'Store below 25°C away from heat.',
        'tags': ['diabetic foot', 'urea cream', 'cracked heels', 'foot care']
    },
    {
        'name': 'Forxiga 10mg Tablet',
        'slug': 'forxiga-10mg-tablet',
        'sku': 'MED-DIA-013',
        'category_slug': 'diabetes-care',
        'brand_name': 'AstraZeneca',
        'manufacturer': 'AstraZeneca Pharma India Ltd',
        'generic_name': 'Dapagliflozin Tablets 10mg',
        'composition': 'Dapagliflozin Propanediol (10mg)',
        'dosage_form': 'TABLET',
        'strength': '10mg',
        'pack_size': 'Strip of 14 tablets',
        'price': Decimal('680.00'),
        'discount_percent': Decimal('14.00'),
        'stock_quantity': 180,
        'rating': Decimal('4.9'),
        'review_count': 690,
        'prescription_required': True,
        'featured': False,
        'trending': True,
        'bestseller': False,
        'short_description': 'Cardiorenal protective SGLT2 inhibitor managing type-2 diabetes and reducing heart failure hospitalization.',
        'detailed_description': 'Dapagliflozin selectively inhibits sodium-glucose co-transporter 2, promoting glycosuria, reducing body weight, and offering proven renal-protective benefits.',
        'directions': 'Take 1 tablet once daily in the morning with a full glass of water.',
        'warnings': 'Prescription required. Stay well hydrated. Check for ketoacidosis if feeling unusually nauseous.',
        'storage_information': 'Store below 30°C in original packaging.',
        'tags': ['dapagliflozin', 'sglt2', 'cardiorenal', 'rx']
    },
]
