# Generated by Django 5.1.15 on 2026-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order Update'), ('PAYMENT', 'Payment Alert'), ('APPOINTMENT', 'Appointment Alert'), ('PRESCRIPTION', 'Prescription Status'), ('PROMOTION', 'Promotions & Offers'), ('SYSTEM', 'System Announcement')], db_index=True, default='SYSTEM', max_length=20),
        ),
    ]
