# Generated by Django 5.1.15 on 2026-09-10 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('doctors', '0003_doctorprofile_avatar_url_doctorprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBlockedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(default='Doctor Unavailable / Leave', max_length=255)),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Doctor Blocked Dates',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_provider',
            field=models.CharField(choices=[('WEBRTC_SECURE', 'MediSwift Secure WebRTC'), ('JITSI', 'Jitsi Meet'), ('ZOOM', 'Zoom Healthcare')], default='WEBRTC_SECURE', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_room_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active / In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Secure WebRTC / Telehealth room link', max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('NO_SHOW', 'No Show')], db_index=True, default='CONFIRMED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status', 'scheduled_at'], name='appointment_doctor__5ddb45_idx'),
        ),
        migrations.AddField(
            model_name='doctorblockeddate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='doctors.doctorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorblockeddate',
            unique_together={('doctor', 'date')},
        ),
    ]
