# Generated by Django 5.1.15 on 2026-09-05 03:45

import apps.prescriptions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to=apps.prescriptions.models.prescription_upload_path, validators=[apps.prescriptions.models.validate_prescription_file])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('doctor_name', models.CharField(blank=True, help_text='Prescribing Doctor Name', max_length=150)),
                ('patient_notes', models.TextField(blank=True, help_text='Notes added by patient')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('pharmacist_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_products', models.ManyToManyField(blank=True, related_name='associated_prescriptions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
