# Generated by Django 5.1.15 on 2026-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='provider_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway',
        ),
        migrations.AddField(
            model_name='payment',
            name='internal_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_details',
            field=models.JSONField(blank=True, default=dict, help_text='Non-sensitive payment instrument details'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('PAYTM', 'Paytm'), ('PHONEPE', 'PhonePe'), ('STRIPE', 'Stripe'), ('UPI', 'UPI Direct'), ('COD', 'Cash on Delivery'), ('CARD_MOCK', 'Debit / Credit Card')], default='RAZORPAY', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
