# Generated by Django 5.1.15 on 2026-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Direct profile image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(default='New Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_available_for_in_person',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
