# Generated by Django 5.1.15 on 2026-09-05 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Brand logo URL', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Curated category visual / banner URL', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='List of gallery image URLs'),
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='directions',
            field=models.TextField(blank=True, help_text='Directions for safe use'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Primary product image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Detailed ingredients and active salts'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original MRP in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective selling price in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('4.50'), max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_information',
            field=models.TextField(blank=True, help_text='Storage conditions, e.g. store below 25°C'),
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 650mg, 100ml, 1% w/w', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Keywords & health tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='warnings',
            field=models.TextField(blank=True, help_text='Safety precautions & contraindications'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('CREAM', 'Cream'), ('GEL', 'Gel'), ('DROPS', 'Drops'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('INHALER', 'Inhaler'), ('STRIP', 'Test Strip'), ('DEVICE', 'Healthcare Device'), ('LIQUID', 'Liquid'), ('LOTION', 'Lotion'), ('OTHER', 'Other')], default='TABLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'requires_prescription'], name='products_pr_is_acti_45f000_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'trending', 'bestseller'], name='products_pr_feature_af8135_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating', 'price'], name='products_pr_rating_2995d7_idx'),
        ),
    ]
