# Generated by Django 5.1.15 on 2026-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_logo_url_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_status',
            field=models.CharField(blank=True, db_index=True, default='NEEDS_VERIFIED_IMAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
