# Generated by Django 5.1.15 on 2026-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_source_product_image_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Descriptive pharmaceutical packaging alt text', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_license',
            field=models.CharField(blank=True, help_text='e.g. Proprietary / Authorized Distributor / Editorial', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='license',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(blank=True, default='NEEDS_VERIFIED_IMAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_source',
            field=models.CharField(blank=True, help_text='Origin e.g. Manufacturer Official / Authorized Distributor', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_status',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'Verified Authentic Photograph'), ('NEEDS_VERIFIED_IMAGE', 'Awaiting Verified Packshot'), ('FALLBACK_GENERATED', 'Clinical Specification Fallback')], db_index=True, default='NEEDS_VERIFIED_IMAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
