# Generated by Django 5.1.15 on 2026-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_alt_text_product_image_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, help_text='Official source link e.g. brand portal or catalog', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date & time when image was verified', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Verifier name or employee ID', max_length=150),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_status',
            field=models.CharField(blank=True, choices=[('MISSING', 'Missing Image'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], db_index=True, default='MISSING', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/packshots/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.CharField(blank=True, choices=[('MISSING', 'Missing Image'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], default='MISSING', max_length=50),
        ),
    ]
