# Generated by Django 5.1.15 on 2026-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_source_url_product_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/pending_review/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of image file', max_length=64),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_status',
            field=models.CharField(choices=[('MISSING', 'Missing Image'), ('DOWNLOADED', 'Downloaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], db_index=True, default='PENDING_REVIEW', max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='license_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_status',
            field=models.CharField(blank=True, choices=[('MISSING', 'Missing Image'), ('DOWNLOADED', 'Downloaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], db_index=True, default='MISSING', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/pending_review/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.CharField(blank=True, choices=[('MISSING', 'Missing Image'), ('DOWNLOADED', 'Downloaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], default='PENDING_REVIEW', max_length=50),
        ),
    ]
