# Generated by Django 5.1.15 on 2026-09-12 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_image_file_productimage_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_page_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductImageCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('candidate_image_url', models.URLField(max_length=1000)),
                ('source_page_url', models.URLField(blank=True, max_length=1000)),
                ('source_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('image_title', models.CharField(blank=True, max_length=255)),
                ('detected_alt_text', models.CharField(blank=True, max_length=500)),
                ('rights_note', models.TextField(blank=True, help_text='Rights/license advisory, e.g. Usage permission has not been confirmed.')),
                ('license_url', models.URLField(blank=True, max_length=1000)),
                ('matching_confidence', models.FloatField(default=0.0, help_text='Confidence score 0.0 to 1.0')),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED_FOR_DOWNLOAD', 'Approved for Download'), ('DOWNLOADED', 'Downloaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('BROKEN', 'Broken'), ('DUPLICATE', 'Duplicate'), ('RIGHTS_UNKNOWN', 'Rights Unknown'), ('PRODUCT_MISMATCH', 'Product Mismatch'), ('BLOCKED_SOURCE', 'Blocked Source')], db_index=True, default='DISCOVERED', max_length=50)),
                ('review_reason', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_origin', to='products.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_candidates', to='products.product')),
            ],
            options={
                'ordering': ['-matching_confidence', '-discovered_at'],
                'indexes': [models.Index(fields=['sku', 'status'], name='products_pr_sku_416172_idx'), models.Index(fields=['status', 'matching_confidence'], name='products_pr_status_a10c49_idx')],
            },
        ),
    ]
