# Generated by Django 5.1.15 on 2026-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_height_productimage_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_real_product_photo',
            field=models.BooleanField(db_index=True, default=False, help_text='True strictly when photo is an authentic verified physical packaging photo'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_real_product_photo',
            field=models.BooleanField(default=False, help_text='True strictly when photo is an authentic verified physical packaging photo'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='requires_real_photo_replacement',
            field=models.BooleanField(default=True, help_text='True if this asset is a temporary demo visual requiring replacement'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_type',
            field=models.CharField(blank=True, default='MANUAL_UPLOAD', help_text='e.g. AI_GENERATED_DEMO, MANUAL_UPLOAD, OFFICIAL_PORTAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_status',
            field=models.CharField(blank=True, choices=[('MISSING', 'Missing Image'), ('DOWNLOADED', 'Downloaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('AI_DEMO_ONLY', 'AI Generated Demo Visual'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], db_index=True, default='MISSING', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_status',
            field=models.CharField(choices=[('MISSING', 'Missing Image'), ('DOWNLOADED', 'Downloaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('AI_DEMO_ONLY', 'AI Generated Demo Visual'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], db_index=True, default='PENDING_REVIEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='mime_type',
            field=models.CharField(blank=True, default='image/webp', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.CharField(blank=True, choices=[('MISSING', 'Missing Image'), ('DOWNLOADED', 'Downloaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified Authentic Photograph'), ('AI_DEMO_ONLY', 'AI Generated Demo Visual'), ('REJECTED', 'Rejected Image'), ('BROKEN', 'Broken Image URL / Asset'), ('DUPLICATE', 'Duplicate Image Mapping')], default='PENDING_REVIEW', max_length=50),
        ),
    ]
