# Generated by Django 6.1 on 2026-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_availability_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Active salt / chemical composition e.g. Paracetamol (650mg)', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='discount_percent',
            field=models.PositiveIntegerField(default=15, help_text='Discount percentage against MRP'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup / Suspension'), ('ointment', 'Ointment / Gel / Cream'), ('injection', 'Injection / Vial'), ('drops', 'Eye / Ear Drops'), ('inhaler', 'Inhaler / Respules'), ('powder', 'Powder / Sachet')], db_index=True, default='tablet', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='how_to_use',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price in INR (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='packaging',
            field=models.CharField(blank=True, default='Strip of 10 tablets', help_text='Package configuration e.g. Strip of 15 tablets, Bottle of 100ml', max_length=120),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price in INR (₹)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['composition'], name='core_api_me_composi_fbc045_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['dosage_form'], name='core_api_me_dosage__a47df3_idx'),
        ),
    ]
